### ISSUE TITLE
UT query_edgekeys_test failed

### ISSUE THREAD

**Issue by darionyaphet** [vesoft-inc/nebula#1307]
```
Missing separate debuginfos, use: dnf debuginfo-install libgcc-8.3.1-2.fc29.x86_64 xz-libs-5.2.4-3.fc29.x86_64
(gdb) bt
#0  __GI_raise (sig=sig@entry=6) at ../sysdeps/unix/sysv/linux/raise.c:50
#1  0x00007fed17eaf895 in __GI_abort () at abort.c:79
#2  0x0000000001ae5bad in google::DumpStackTraceAndExit() [clone .cold.21] ()
#3  0x000000000292448d in google::LogMessage::Fail() ()
#4  0x00000000029289dc in google::LogMessage::SendToLog() ()
#5  0x000000000292418d in google::LogMessage::Flush() ()
#6  0x0000000002924979 in google::LogMessageFatal::~LogMessageFatal() ()
#7  0x0000000001bacd5d in nebula::storage::QueryEdgeKeysTest_SimpleTest_Test::TestBody (this=0x7fed17ab2b60) at /home/darion.wang/nebula/src/storage/test/QueryEdgeKeysTest.cpp:81
#8  0x00000000027c20ea in void testing::internal::HandleExceptionsInMethodIfSupported<testing::Test, void>(testing::Test*, void (testing::Test::*)(), char const*) ()
#9  0x00000000027ba00a in testing::Test::Run() ()
#10 0x00000000027ba158 in testing::TestInfo::Run() ()
#11 0x00000000027ba235 in testing::TestCase::Run() ()
#12 0x00000000027ba70c in testing::internal::UnitTestImpl::RunAllTests() ()
#13 0x00000000027c256a in bool testing::internal::HandleExceptionsInMethodIfSupported<testing::internal::UnitTestImpl, bool>(testing::internal::UnitTestImpl*, bool (testing::internal::UnitTestImpl::*)(), char const*) ()
#14 0x00000000027ba7ff in testing::UnitTest::Run() ()
#15 0x0000000001bb16d2 in RUN_ALL_TESTS () at /opt/nebula/third-party/include/gtest/gtest.h:2233
#16 0x0000000001bad394 in main (argc=1, argv=0x7ffc0001dd88) at /home/darion.wang/nebula/src/storage/test/QueryEdgeKeysTest.cpp:100
```

**Comment by CPWstatic** [comment]
As far as i know, it is now reproduced in latest version of nebula1.0 and nebula2.0. I'll close it firstly.
