### ISSUE TITLE
The storaged is crashed when lookup_concurrently=true

### ISSUE THREAD

**Issue by tong-hao** [vesoft-inc/nebula#2479]
**Describe the bug (__must be provided__)**
The storaged is crashed when lookup_concurrently=true
version:1.2.1
```
    @          0x2454277 _ZN6nebula14NebulaKeyUtils19checkAndCastVariantENS_4cpp213SupportedTypeERN5boost7variantIlJdbNSt7__cxx1112basic_stringIcSt11char_traitsIcESaIcEEEEEE
    @          0x245a0e2 _ZN6nebula7storage13IndexExecutorINS0_4cpp215LookUpIndexRespEE12makeScanPairB5cxx11Eii
    @          0x2456fb6 nebula::storage::IndexExecutor<>::getIndexKey()
    @          0x245865e _ZZN6nebula7storage13IndexExecutorINS0_4cpp215LookUpIndexRespEE29executeExecutionPlanForVertexERKSt6vectorIiSaIiEEENUlvE_clEv
    @          0x2467edc _ZN5folly6detail8function14FunctionTraitsIFvvEE9callSmallIZN6nebula7storage13IndexExecutorINS7_4cpp215LookUpIndexRespEE29executeExecutionPlanForVertexERKSt6vectorIiSaIiEEEUlvE_EEvRNS1_4DataE
    @          0x22e51b0 folly::detail::function::FunctionTraits<>::operator()()
    @          0x2332d7d apache::thrift::concurrency::FunctionRunner::run()
    @          0x23332a7 apache::thrift::concurrency::ThreadManager::Task::run()
    @          0x2369c69 apache::thrift::concurrency::ThreadManager::ImplT<>::Worker<>::run()
    @          0x338c527 apache::thrift::concurrency::PthreadThread::threadMain()
    @     0x7fdcda8b0e24 start_thread
    @     0x7fdcda5de34c __clone
```

- gdb
```
#17 0x00000000022e8da3 in boost::variant<long, double, bool, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > >::operator=<long> (this=0x7fdcd1c4abc8, rhs=@0x7fdc806ed588: 1)
    at /opt/vesoft/third-party/include/boost/variant/variant.hpp:2257
#18 0x0000000002454278 in nebula::NebulaKeyUtils::checkAndCastVariant (sType=nebula::cpp2::SupportedType::INT, v=...) at /root/nebula_deploy/nebula-1.2.1/src/common/utils/NebulaKeyUtils.h:337
#19 0x000000000245a0e3 in nebula::storage::IndexExecutor<nebula::storage::cpp2::LookUpIndexResp>::makeScanPair[abi:cxx11](int, int) (this=0x7fdcd1c6cf00, partId=84, indexId=9)
    at /root/nebula_deploy/nebula-1.2.1/src/storage/index/IndexExecutor.inl:140
#20 0x0000000002456fb7 in nebula::storage::IndexExecutor<nebula::storage::cpp2::LookUpIndexResp>::getIndexKey (this=0x7fdcd1c6cf00, part=84, keys=...) at /root/nebula_deploy/nebula-1.2.1/src/storage/index/IndexExecutor.inl:387
#21 0x000000000245865f in nebula::storage::IndexExecutor<nebula::storage::cpp2::LookUpIndexResp>::executeExecutionPlanForVertex(std::vector<int, std::allocator<int> > const&)::{lambda()#1}::operator()() (__closure=0x7fdcbf4a3310)
    at /root/nebula_deploy/nebula-1.2.1/src/storage/index/IndexExecutor.inl:321
#22 0x0000000002467edd in folly::detail::function::FunctionTraits<void ()>::callSmall<nebula::storage::IndexExecutor<nebula::storage::cpp2::LookUpIndexResp>::executeExecutionPlanForVertex(std::vector<int, std::allocator<int> > const&)::{lambda()#1}>(folly::detail::function::Data&) (p=...) at /opt/vesoft/third-party/include/folly/Function.h:313
```

```
(gdb) bt
#0  0x00000000033ee1a0 in folly::Expected<long, folly::ConversionCode> folly::detail::str_to_integral<long>(folly::Range<char const*>*) ()
#1  0x00000000022f8487 in folly::detail::convertTo<long> (src=0x7f36d2bfb400) at /opt/vesoft/third-party/include/folly/Conv.h:1149
#2  0x00000000022f350a in folly::parseTo<long> (src=..., out=@0x7f36d2bfb4b0: 0) at /opt/vesoft/third-party/include/folly/Conv.h:1190
#3  0x00000000022eecfb in folly::detail::parseToWrap<long> (sp=..., out=@0x7f36d2bfb4b0: 0) at /opt/vesoft/third-party/include/folly/Conv.h:1465
#4  0x00000000022e9eb4 in folly::to<long> (src=...) at /opt/vesoft/third-party/include/folly/Conv.h:1513
#5  0x00000000022e5e5b in folly::to<long, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > > (src=...) at /opt/vesoft/third-party/include/folly/Conv.h:1500
#6  0x00000000022dbe3e in nebula::Expression::toInt (value=...) at /root/nebula_deploy/nebula-1.2.1/src/common/filter/Expressions.h:387
#7  0x0000000002454261 in nebula::NebulaKeyUtils::checkAndCastVariant (sType=nebula::cpp2::SupportedType::INT, v=...) at /root/nebula_deploy/nebula-1.2.1/src/common/utils/NebulaKeyUtils.h:337
#8  0x000000000245a0e3 in nebula::storage::IndexExecutor<nebula::storage::cpp2::LookUpIndexResp>::makeScanPair[abi:cxx11](int, int) (this=0x7f36de202100, partId=5, indexId=9)
    at /root/nebula_deploy/nebula-1.2.1/src/storage/index/IndexExecutor.inl:140
#9  0x0000000002456fb7 in nebula::storage::IndexExecutor<nebula::storage::cpp2::LookUpIndexResp>::getIndexKey (this=0x7f36de202100, part=5, keys=...) at /root/nebula_deploy/nebula-1.2.1/src/storage/index/IndexExecutor.inl:387
#10 0x000000000245865f in nebula::storage::IndexExecutor<nebula::storage::cpp2::LookUpIndexResp>::executeExecutionPlanForVertex(std::vector<int, std::allocator<int> > const&)::{lambda()#1}::operator()() (__closure=0x7f36eedc56d0)
    at /root/nebula_deploy/nebula-1.2.1/src/storage/index/IndexExecutor.inl:321
```

- code: multithread modify v ??
`v = Expression::toInt(v);`

**Your Environments (__must be provided__)**

* OS: CentOS Linux release 7.4.1708 (Core)
* Compliler: g++ (GCC) 4.8.5
* CPU: Intel(R) Xeon(R) CPU E5-2640 v3 @ 2.60GHz

**How To Reproduce(__must be provided__)**
lookup on xxx where xxx

**Comment by bright-starry-sky** [comment]
Thanks for your issue report, would you like further to fix it ? if yes，please refer to the #2417 if you like.

**Comment by bright-starry-sky** [comment]
A patch is provided, could you help me verify this in your environment? thanks a lot.
https://github.com/vesoft-inc/nebula/pull/2481

**Comment by wey-gu** [comment]
Will close it as it's been inactive for days. Feel free to reopen it.
