### ISSUE TITLE
`$var;limit` cause graphd to crash

### ISSUE THREAD

**Issue by jievince** [vesoft-inc/nebula#2637]
```
(root@nebula) [nba]> $a=FETCH PROP ON * "Tony Parker";limit 1
2021/07/07 15:48:43 [ERROR] Failed to reconnect, Failed to open transport, error: dial tcp 127.0.0.1:38996: connect: connection refused
2021/07/07 15:48:43 Loop error, Failed to open transport, error: dial tcp 127.0.0.1:38996: connect: connection refused

Bye root!
Wed, 07 Jul 2021 15:48:43 CST

panic: Loop error, Failed to open transport, error: dial tcp 127.0.0.1:38996: connect: connection refused

goroutine 1 [running]:
log.Panicf(0x646161, 0xe, 0xc0000d1e78, 0x1, 0x1)
        /opt/hostedtoolcache/go/1.16.4/x64/src/log/log.go:361 +0xc5
main.main()
        /home/runner/work/nebula-console/nebula-console/main.go:419 +0x4f3
```

**Comment by Shylock-Hg** [comment]
Closed by https://github.com/vesoft-inc/nebula/pull/2570
