### ISSUE TITLE
Error connecting nebula with console on M1

### ISSUE THREAD

**Issue by foesa-yang** [vesoft-inc/nebula#2834]
Nebula Graph version 2.5.0
Apple M1 chip
When I use docker to connect to the console, the following problems occur.
```
foesa@foesasdeMacBook-Pro nebula-docker-compose % docker run --rm -ti --network nebula-docker-compose_nebula-net --entrypoint=/bin/sh vesoft/nebula-console:v2.5.0
WARNING: The requested image's platform (linux/amd64) does not match the detected host platform (linux/arm64/v8) and no specific platform was requested

/ # nebula-console -u root -p 23 --address=graphd --port=9669
2021/09/10 01:47:47 [INFO] connection pool is initialized successfully
2021/09/10 01:47:47 Fail to create a new session from connection pool, failed to open transport, error: dial tcp 172.21.0.9:9669: connect: connection refused
panic: Fail to create a new session from connection pool, failed to open transport, error: dial tcp 172.21.0.9:9669: connect: connection refused

goroutine 1 [running]:
log.Panicf(0x7ac363, 0x35, 0xc000061e98, 0x1, 0x1)
	/usr/local/go/src/log/log.go:345 +0xc0
main.main()
	/usr/src/main.go:364 +0x8cd
```
And the state is `unhealthy`
```
foesa@foesasdeMacBook-Pro nebula-docker-compose % docker-compose ps
              Name                             Command                   State                                                          Ports                                                  
-----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------
nebula-docker-compose_graphd1_1     /usr/local/nebula/bin/nebu ...   Up (healthy)     0.0.0.0:61914->19669/tcp, 0.0.0.0:61912->19670/tcp, 0.0.0.0:61913->9669/tcp                              
nebula-docker-compose_graphd2_1     /usr/local/nebula/bin/nebu ...   Up (healthy)     0.0.0.0:61919->19669/tcp, 0.0.0.0:61917->19670/tcp, 0.0.0.0:61918->9669/tcp                              
nebula-docker-compose_graphd_1      /usr/local/nebula/bin/nebu ...   Up (healthy)     0.0.0.0:61915->19669/tcp, 0.0.0.0:61916->19670/tcp, 0.0.0.0:9669->9669/tcp                               
nebula-docker-compose_metad0_1      /usr/local/nebula/bin/nebu ...   Up (unhealthy)   0.0.0.0:61901->19559/tcp, 0.0.0.0:61899->19560/tcp, 0.0.0.0:61900->9559/tcp, 9560/tcp                    
nebula-docker-compose_metad1_1      /usr/local/nebula/bin/nebu ...   Up (unhealthy)   0.0.0.0:61892->19559/tcp, 0.0.0.0:61893->19560/tcp, 0.0.0.0:61894->9559/tcp, 9560/tcp                    
nebula-docker-compose_metad2_1      /usr/local/nebula/bin/nebu ...   Up (unhealthy)   0.0.0.0:61896->19559/tcp, 0.0.0.0:61897->19560/tcp, 0.0.0.0:61898->9559/tcp, 9560/tcp                    
nebula-docker-compose_storaged0_1   /usr/local/nebula/bin/nebu ...   Up (unhealthy)   0.0.0.0:61902->19779/tcp, 0.0.0.0:61903->19780/tcp, 9777/tcp, 9778/tcp, 0.0.0.0:61904->9779/tcp, 9780/tcp
nebula-docker-compose_storaged1_1   /usr/local/nebula/bin/nebu ...   Up (unhealthy)   0.0.0.0:61910->19779/tcp, 0.0.0.0:61911->19780/tcp, 9777/tcp, 9778/tcp, 0.0.0.0:61909->9779/tcp, 9780/tcp
nebula-docker-compose_storaged2_1   /usr/local/nebula/bin/nebu ...   Up (unhealthy)   0.0.0.0:61906->19779/tcp, 0.0.0.0:61907->19780/tcp, 9777/tcp, 9778/tcp, 0.0.0.0:61905->9779/tcp, 9780/tcp
```

close #2791

**Comment by HarrisChu** [comment]
https://github.com/vesoft-inc/nebula/issues/2791

**Comment by yixinglu** [comment]
We need to build the ARM-arch docker image for M1, which will include following images:
* vesoft/nebula-dev
* vesoft/nebula-{graphd, storaged, metad}
* vesoft/nebula-console
* vesoft/nebula-importer
* vesoft/nebula-http-gateway
* vesoft/nebula-studio

**Comment by Sophie-Xie** [comment]
Product Committee: not include in v3.0.0

**Comment by wey-gu** [comment]
I think it's crucial to provide at least core arm linux image due to developers with Mac desktop machines since 2020+ are all arm-based and whether to be able to run it with docker on the desktop makes quite some differences for those why would like to access/quick start nebula graph.

One workaround that would be possible is to have the standalone nebula docker image, which is a single docker image, ideally, the x86 image could be runnable in qemu-fmt(emulating x86 in ARM machine).

**Comment by abby-cyber** [comment]
https://github.com/vesoft-inc/nebula-docs-cn/pull/1542/files

**Comment by abby-cyber** [comment]
https://github.com/vesoft-inc/nebula-docs-cn/pull/1542/files

**Comment by abby-cyber** [comment]
#1542
