### ISSUE TITLE
Unwinding the result of subgraph crash the nebula-graphd

### ISSUE THREAD

**Issue by yixinglu** [vesoft-inc/nebula#3477]
**Please check the FAQ documentation before raising an issue**

**Describe the bug (__required__)**

**Your Environments (__required__)**

* OS: `uname -a`
* Compiler: `g++ --version` or `clang++ --version`
* CPU: `lscpu`
* Commit id (e.g. `a3ffc7d8`)

**How To Reproduce(__required__)**

```
(root@nebula) [nba_int_vid]> get subgraph 7 steps from hash("LeBron James") BOTH like yield edges as e | unwind $-.e as es return es
```

backtrace:

```text
gdb> bt
#0  __GI_raise (sig=sig@entry=6) at ../sysdeps/unix/sysv/linux/raise.c:50
#1  0x00007f6216439895 in __GI_abort () at abort.c:79
#2  0x000000000862671d in google::LogMessage::Fail() ()
#3  0x000000000862b4f6 in google::LogMessage::SendToLog() ()
#4  0x00000000086263ee in google::LogMessage::Flush() ()
#5  0x0000000008626c49 in google::LogMessageFatal::~LogMessageFatal() ()
#6  0x00000000044fe36b in nebula::graph::DefaultIter::getColumn (this=0x7f61eb757d00)
    at /home/yee.yi/Workspace/NebulaGraphMatrix/src/graph/context/Iterator.h:179
#7  0x000000000448bc12 in nebula::graph::QueryExpressionContext::getInputProp (this=0x7f61ecdfc1d8, prop="e")
    at /home/yee.yi/Workspace/NebulaGraphMatrix/src/graph/context/QueryExpressionContext.cpp:67
#8  0x0000000007f2c150 in nebula::InputPropertyExpression::eval (this=0x7f61eb7a4c00, ctx=...)
    at /home/yee.yi/Workspace/NebulaGraphMatrix/src/common/expression/PropertyExpression.cpp:67
#9  0x0000000003c59ff1 in nebula::graph::UnwindExecutor::execute (this=0x7f61eb764e40)
    at /home/yee.yi/Workspace/NebulaGraphMatrix/src/graph/executor/query/UnwindExecutor.cpp:29
#10 0x00000000043f64aa in nebula::graph::AsyncMsgNotifyBasedScheduler::execute (this=0x7f61eb700020, executor=0x7f61eb764e40)
    at /home/yee.yi/Workspace/NebulaGraphMatrix/src/graph/scheduler/AsyncMsgNotifyBasedScheduler.cpp:269
#11 0x00000000044343f6 in nebula::graph::AsyncMsgNotifyBasedScheduler::runExecutor(std::vector<folly::Future<nebula::Status>, std::allocator<folly::Future<nebul
a::Status> > >&&, nebula::graph::Executor*, folly::Executor*, std::vector<folly::Promise<nebula::Status>, std::allocator<folly::Promise<nebula::Status> > >&&) c
onst::$_1::operator()<folly::Try<std::vector<nebula::Status, std::allocator<nebula::Status> > > >(folly::Try<std::vector<nebula::Status, std::allocator<nebula::
Status> > >&&) (this=0x7f61eb74ee40, t=...) at /home/yee.yi/Workspace/NebulaGraphMatrix/src/graph/scheduler/AsyncMsgNotifyBasedScheduler.cpp:172
#12 0x0000000004433d7c in folly::Future<std::vector<nebula::Status, std::allocator<nebula::Status> > >::thenTry<nebula::graph::AsyncMsgNotifyBasedScheduler::run
Executor(std::vector<folly::Future<nebula::Status>, std::allocator<folly::Future<nebula::Status> > >&&, nebula::graph::Executor*, folly::Executor*, std::vector<
folly::Promise<nebula::Status>, std::allocator<folly::Promise<nebula::Status> > >&&) const::$_1>(nebula::graph::AsyncMsgNotifyBasedScheduler::runExecutor(std::v
ector<folly::Future<nebula::Status>, std::allocator<folly::Future<nebula::Status> > >&&, nebula::graph::Executor*, folly::Executor*, std::vector<folly::Promise<
nebula::Status>, std::allocator<folly::Promise<nebula::Status> > >&&) const::$_1&&) &&::{lambda(folly::Executor::KeepAlive<folly::Executor>&&, folly::Try<std::v
ector<nebula::Status, std::allocator<nebula::Status> > >&&)#1}::operator()(folly::Executor::KeepAlive<folly::Executor>&&, folly::Try<std::vector<nebula::Status,
 std::allocator<nebula::Status> > >&&) (this=0x7f61eb74ee40, t=...) at /opt/vesoft/third-party/2.0/include/folly/futures/Future-inl.h:947
#13 0x0000000004433cea in folly::futures::detail::CoreCallbackState<folly::Unit, folly::Future<std::vector<nebula::Status, std::allocator<nebula::Status> > >::t
henTry<nebula::graph::AsyncMsgNotifyBasedScheduler::runExecutor(std::vector<folly::Future<nebula::Status>, std::allocator<folly::Future<nebula::Status> > >&&, n
ebula::graph::Executor*, folly::Executor*, std::vector<folly::Promise<nebula::Status>, std::allocator<folly::Promise<nebula::Status> > >&&) const::$_1>(nebula::
graph::AsyncMsgNotifyBasedScheduler::runExecutor(std::vector<folly::Future<nebula::Status>, std::allocator<folly::Future<nebula::Status> > >&&, nebula::graph::E
xecutor*, folly::Executor*, std::vector<folly::Promise<nebula::Status>, std::allocator<folly::Promise<nebula::Status> > >&&) const::$_1&&) &&::{lambda(folly::Ex
ecutor::KeepAlive<folly::Executor>&&, folly::Try<std::vector<nebula::Status, std::allocator<nebula::Status> > >&&)#1}>::invoke<folly::Executor::KeepAlive<folly:
:Executor>, folly::Try<std::vector<nebula::Status, std::allocator<nebula::Status> > > >(folly::Executor::KeepAlive<folly::Executor>&&, folly::Try<std::vector<ne
bula::Status, std::allocator<nebula::Status> > >&&) (this=0x7f61eb74ee40, args=..., args=...)
    at /opt/vesoft/third-party/2.0/include/folly/futures/Future-inl.h:134
```

**Expected behavior**

**Additional context**

**Comment by nevermore3** [comment]
maybe we should  prohibit mixing cypher and ngql sentences
