### ISSUE TITLE
cannot exit metad leader if the job is running 

### ISSUE THREAD

**Issue by HarrisChu** [vesoft-inc/nebula#3749]
if there's a job running, metad leader cannot exit

```
Thread 14 (Thread 0x7effc0bff700 (LWP 125785)):
#0  0x00007efff4e8554d in __lll_lock_wait () from /lib64/libpthread.so.0
#1  0x00007efff4e80e9b in _L_lock_883 () from /lib64/libpthread.so.0
#2  0x00007efff4e80d68 in pthread_mutex_lock () from /lib64/libpthread.so.0
#3  0x00000000011e1322 in nebula::meta::JobManager::jobFinished(int, nebula::meta::cpp2::JobStatus) ()
#4  0x0000000001209f68 in nebula::meta::LeaderBalanceJobExecutor::executeInternal() ()
#5  0x00000000011f7418 in nebula::meta::MetaJobExecutor::execute() ()
#6  0x00000000011dc2e6 in nebula::meta::JobManager::runJobInternal(nebula::meta::JobDescription const&, nebula::meta::JobManager::JbOp) ()
#7  0x00000000011e1f62 in nebula::meta::JobManager::scheduleThread() ()
#8  0x00000000029a1090 in execute_native_thread_routine ()
#9  0x00007efff4e7eea5 in start_thread () from /lib64/libpthread.so.0
#10 0x00007efff4ba79fd in clone () from /lib64/libc.so.6
```

**Comment by HarrisChu** [comment]
https://github.com/vesoft-inc/nebula/issues/3636

seems root cause is this issue
