### ISSUE TITLE
I meet some issue (Bug) when I traverse vertex causing the nebula-graphd crashed

### ISSUE THREAD

**Issue by Milittle** [vesoft-inc/nebula#4302]
**Describe the bug (__required__)**

When I concurrent run some tests. some just like these:

```
MATCH (v:Tag1)-[*0…0] where (properties(v).name contains “xxx”) RETURN DISTINCT vs;
```

the nebula-graphd service crashed and i pull the backtrace the below, I see the source code then guess the vector access out of index.

```
(gdb) bt
#0  0x00007ff9b1d0f410 in ?? ()
#1  0x00000000025f44da in std::char_traits<char>::compare (__n=<optimized out>, __s2=0x2659a6f <nebula::kTag> "_tag", __s1=<optimized out>)
    at /install_temp/gcc-10.2.0/gcc-10.2.0/x86_64-pc-linux-gnu/libstdc++-v3/include/bits/char_traits.h:347
#2  std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >::compare (this=0x7ff9a7b59340, __s=0x2659a6f <nebula::kTag> "_tag")
    at /install_temp/gcc-10.2.0/gcc-10.2.0/x86_64-pc-linux-gnu/libstdc++-v3/include/bits/basic_string.tcc:1435
#3  0x000000000125f8f3 in nebula::graph::GetNeighborsIter::getVertex(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&) const ()
    at /install_temp/gcc-10.2.0/gcc-10.2.0/x86_64-pc-linux-gnu/libstdc++-v3/include/bits/char_traits.h:395
#4  0x000000000125fdbf in nebula::graph::GetNeighborsIter::getVertices() () at /install_temp/gcc-10.2.0/gcc-10.2.0/x86_64-pc-linux-gnu/libstdc++-v3/include/bits/char_traits.h:395
#5  0x0000000001195a6a in nebula::graph::TraverseExecutor::buildInterimPath(nebula::graph::GetNeighborsIter*) ()
    at /install_temp/gcc-10.2.0/gcc-10.2.0/x86_64-pc-linux-gnu/libstdc++-v3/include/bits/char_traits.h:395
#6  0x0000000001198147 in nebula::graph::TraverseExecutor::handleResponse(nebula::storage::StorageRpcResponse<nebula::storage::cpp2::GetNeighborsResponse>&&) ()
    at /install_temp/gcc-10.2.0/gcc-10.2.0/x86_64-pc-linux-gnu/libstdc++-v3/include/bits/char_traits.h:395
#7  0x0000000001198fcc in nebula::graph::TraverseExecutor::getNeighbors()::{lambda(nebula::storage::StorageRpcResponse<nebula::storage::cpp2::GetNeighborsResponse>&&)#1}::operator()(nebula::storage::StorageRpcResponse<nebula::storage::cpp2::GetNeighborsResponse>&&) () at /install_temp/gcc-10.2.0/gcc-10.2.0/x86_64-pc-linux-gnu/libstdc++-v3/include/bits/char_traits.h:395
#8  0x0000000001199447 in _ZN5folly6detail8function14FunctionTraitsIFvRNS_7futures6detail8CoreBaseEONS_8Executor9KeepAliveIS7_EEPNS_17exception_wrapperEEE9callSmallIZNS4_4CoreIN6nebula7storage18StorageRpcResponseINSI_4cpp220GetNeighborsResponseEEEE11setCallbackIZNS4_10FutureBaseISM_E18thenImplementationIZNOS_6FutureISM_E9thenValueIZNSH_5graph16TraverseExecutor12getNeighborsEvEUlOSM_E_EENSS_INS4_19valueCallableResultISM_T_E10value_typeEEEOS10_EUlSA_ONS_3TryISM_EEE_NS4_25tryExecutorCallableResultISM_S18_vEEEENSt9enable_ifIXsrNT0_13ReturnsFutureE5valueENS1C_6ReturnEE4typeES14_S1C_NS4_18InlineContinuationEEUlSA_S17_E_EEvS14_OSt10shared_ptrINS_14RequestContextEES1H_EUlS6_SA_SC_E_EEvS6_SA_SC_RNS1_4DataE () at /install_temp/gcc-10.2.0/gcc-10.2.0/x86_64-pc-linux-gnu/libstdc++-v3/include/bits/char_traits.h:395
#9  0x0000000002004f2c in ?? () at /install_temp/gcc-10.2.0/gcc-10.2.0/x86_64-pc-linux-gnu/libstdc++-v3/include/bits/char_traits.h:395
#10 0x0000000001daf8f7 in virtual thunk to apache::thrift::concurrency::FunctionRunner::run() () at /install_temp/gcc-10.2.0/gcc-10.2.0/x86_64-pc-linux-gnu/libstdc++-v3/include/bits/char_traits.h:395
#11 0x0000000001ef2468 in apache::thrift::concurrency::ThreadManager::Impl::Worker::run() () at /install_temp/gcc-10.2.0/gcc-10.2.0/x86_64-pc-linux-gnu/libstdc++-v3/include/bits/char_traits.h:395
#12 0x0000000001ef456e in apache::thrift::concurrency::PthreadThread::threadMain(void*) () at /install_temp/gcc-10.2.0/gcc-10.2.0/x86_64-pc-linux-gnu/libstdc++-v3/include/bits/char_traits.h:395
#13 0x00007ff9b1d77f4b in ?? ()
#14 0x0000000000000000 in ?? ()
```

then I put some new log into here, print some message about `tagPropNameList` and `propList.values`. the pair message can not matched: you can see the follow logs:

```
Print for crash xxx tagPropNameList size: 2
Print for crash xxx tagPropNameList value: JZXPFFHYJXPXUPJZWJJC
Print for crash xxx tagPropNameList value: _tag
Print for crash xxx propList size: 8
Print for crash xxx propList value: "EoGxE3QlrScIeHSPamsFIDauw5ZBHW3s80b5REA2uWfXBJExRlSM1e2NWYFM2zMtJmWK0895F99P4bzFtlEaFLBdqODB2RDvCsRo"
Print for crash xxx propList value: "908318010425663232"
Print for crash xxx propList value: "1"
Print for crash xxx propList value: "SEYJVNWKJUTPTIEAMLMJA,SEYJVNWKJUTPTIEAMLMJB,"
Print for crash xxx propList value: "SEYJVNWKJUTPTIEAMLMJ"
Print for crash xxx propList value: "graphServiceEntity_GRAPH_875146890205947392"
Print for crash xxx propList value: NULL
Print for crash xxx propList value: 96310

Print for crash xxx tagPropNameList size: 2
Print for crash xxx tagPropNameList value: BJAGLASCDJIFBCSZFHYH
Print for crash xxx tagPropNameList value: _tag
Print for crash xxx propList size: 2
Print for crash xxx propList value: "cqwvfewxpfvkxewqdi"
Print for crash xxx propList value: 164179

Print for crash xxx tagPropNameList size: 2
Print for crash xxx tagPropNameList value: QYQCYTIOVJAIBZURBPEV
Print for crash xxx tagPropNameList value: _tag
Print for crash xxx propList size: 2
Print for crash xxx propList value: "LZDLCKKLMYFAZRRVLUIS"
Print for crash xxx propList value: 164185

Print for crash xxx tagPropNameList size: 2
Print for crash xxx tagPropNameList value: JZXPFFHYJXPXUPJZWJJC
Print for crash xxx tagPropNameList value: _tag
Print for crash xxx propList size: 8
Print for crash xxx propList value: "EoGxE3QlrScIeHSPamsFIDauw5ZBHW3s80b5REA2uWfXBJExRlSM1e2NWYFM2zMtJmWK0895F99P4bzFtlEaFLBdqODB2RDvCsRo"
Print for crash xxx propList value: "908318010425663232"
Print for crash xxx propList value: "1"
Print for crash xxx propList value: "SEYJVNWKJUTPTIEAMLMJA,SEYJVNWKJUTPTIEAMLMJB,"
Print for crash xxx propList value: "SEYJVNWKJUTPTIEAMLMJ"
Print for crash xxx propList value: "graphServiceEntity_GRAPH_875146890205947392"
Print for crash xxx propList value: NULL
Print for crash xxx propList value: 96310

Print for crash xxx tagPropNameList size: 2
Print for crash xxx tagPropNameList value: BJAGLASCDJIFBCSZFHYH
Print for crash xxx tagPropNameList value: _tag
Print for crash xxx propList size: 2
Print for crash xxx propList value: "cqwvfewxpfvkxewqdi"
Print for crash xxx propList value: 164179

Print for crash xxx tagPropNameList size: 2
Print for crash xxx tagPropNameList value: QYQCYTIOVJAIBZURBPEV
Print for crash xxx tagPropNameList value: _tag
Print for crash xxx propList size: 2
Print for crash xxx propList value: "LZDLCKKLMYFAZRRVLUIS"
Print for crash xxx propList value: 164185

vertex: ("908318010425663232") Tag: DCIJPMUWZPRLJXAUFUOW1, JZXPFFHYJXPXUPJZWJJC:"EoGxE3QlrScIeHSPamsFIDauw5ZBHW3s80b5REA2uWfXBJExRlSM1e2NWYFM2zMtJmWK0895F99P4bzFtlEaFLBdqODB2RDvCsRo"Tag: MWVJTWTLCWQDVJKELCBP1, BJAGLASCDJIFBCSZFHYH:"cqwvfewxpfvkxewqdi"Tag: IOOHWGWJWUROGATHQQGD1, QYQCYTIOVJAIBZURBPEV:"LZDLCKKLMYFAZRRVLUIS" size: 1
```

I think the above logs can prove our program, there have some logic can not match the PropIndex's colIdx. sorry for my bad english. 

If you have any idea about this problem, pls help me located this. thx.

**How To Reproduce(__required__)**

because I run the concurrent tests, at now, I can not give the reproduce steps, but if you have idea, pls tell me how to do this.(because if i run test one by one, the service is normal, but i run concurrently, the service will be down)

thanks for your supporting.

1. Step 1
2. Step 2
3. Step 3

**Comment by wey-gu** [comment]
Interesting, so this pattern was to match vertices with/out any edges connected to them?

PS. here is the runnable query and plan for it

```
(root@nebula) [basketballplayer]> MATCH (v:player)-[*0..0]-() where (properties(v).name contains "a") RETURN DISTINCT v;
+---------------------------------------------------------------+
| v                                                             |
+---------------------------------------------------------------+
| ("player104" :player{age: 32, name: "Marco Belinelli"})       |
| ("player116" :player{age: 34, name: "LeBron James"})          |
| ("player105" :player{age: 31, name: "Danny Green"})           |
| ("player145" :player{age: 31, name: "JaVale McGee"})          |
| ("player120" :player{age: 29, name: "James Harden"})          |
| ("player136" :player{age: 45, name: "Steve Nash"})            |
| ("player801" :player{age: 21, name: "Another Name"})          |
| ("player122" :player{age: 30, name: "DeAndre Jordan"})        |
| ("player109" :player{age: 34, name: "Tiago Splitter"})        |
| ("player139" :player{age: 34, name: "Marc Gasol"})            |
| ("player124" :player{age: 33, name: "Rajon Rondo"})           |
| ("player102" :player{age: 33, name: "LaMarcus Aldridge"})     |
| ("player800" :player{age: 23, name: "Foo Bar"})               |
| ("player138" :player{age: 38, name: "Paul Gasol"})            |
| ("player115" :player{age: 40, name: "Kobe Bryant"})           |
| ("player127" :player{age: 42, name: "Vince Carter"})          |
| ("player134" :player{age: 30, name: "Blake Griffin"})         |
| ("player135" :player{age: 28, name: "Damian Lillard"})        |
| ("player128" :player{age: 34, name: "Carmelo Anthony"})       |
| ("player144" :player{age: 47, name: "Shaquille O'Neal"})      |
| ("player108" :player{age: 36, name: "Boris Diaw"})            |
| ("player131" :player{age: 28, name: "Paul George"})           |
| ("player132" :player{age: 24, name: "Giannis Antetokounmpo"}) |
| ("player146" :player{age: 33, name: "Dwight Howard"})         |
| ("player150" :player{age: 20, name: "Luka Doncic"})           |
| ("player125" :player{age: 41, name: "Manu Ginobili"})         |
| ("player107" :player{age: 32, name: "Aron Baynes"})           |
| ("player148" :player{age: 45, name: "Jason Kidd"})            |
| ("player143" :player{age: 23, name: "Kristaps Porzingis"})    |
| ("player103" :player{age: 32, name: "Rudy Gay"})              |
| ("player147" :player{age: 36, name: "Amar'e Stoudemire"})     |
| ("player114" :player{age: 39, name: "Tracy McGrady"})         |
| ("player119" :player{age: 30, name: "Kevin Durant"})          |
| ("player121" :player{age: 33, name: "Chris Paul"})            |
| ("player129" :player{age: 37, name: "Dwyane Wade"})           |
| ("player113" :player{age: 29, name: "Dejounte Murray"})       |
| ("player101" :player{age: 36, name: "Tony Parker"})           |
| ("player111" :player{age: 38, name: "David West"})            |
| ("player142" :player{age: 29, name: "Klay Thompson"})         |
| ("player140" :player{age: 46, name: "Grant Hill"})            |
| ("player100" :player{age: 42, name: "Tim Duncan"})            |
| ("player141" :player{age: 43, name: "Ray Allen"})             |
| ("player133" :player{age: 38, name: "Yao Ming"})              |
| ("player112" :player{age: 29, name: "Jonathon Simmons"})      |
+---------------------------------------------------------------+
Got 44 rows (time spent 13018/14696 us)

Tue, 07 Jun 2022 02:43:47 UTC

(root@nebula) [basketballplayer]> explain MATCH (v:player)-[*0..0]-() where (properties(v).name contains "a") RETURN DISTINCT v;
Execution succeeded (time spent 684/1582 us)

Execution Plan (optimize time 181 us)

-----+----------------+--------------+----------------+--------------------------------------------------
| id | name           | dependencies | profiling data | operator info                                   |
-----+----------------+--------------+----------------+--------------------------------------------------
|  9 | DataCollect    | 8            |                | outputVar: {                                    |
|    |                |              |                |   "colNames": [                                 |
|    |                |              |                |     "v"                                         |
|    |                |              |                |   ],                                            |
|    |                |              |                |   "type": "DATASET",                            |
|    |                |              |                |   "name": "__DataCollect_9"                     |
|    |                |              |                | }                                               |
|    |                |              |                | inputVar: [                                     |
|    |                |              |                |   {                                             |
|    |                |              |                |     "colNames": [                               |
|    |                |              |                |       "v"                                       |
|    |                |              |                |     ],                                          |
|    |                |              |                |     "type": "DATASET",                          |
|    |                |              |                |     "name": "__Dedup_8"                         |
|    |                |              |                |   }                                             |
|    |                |              |                | ]                                               |
|    |                |              |                | kind: ROW                                       |
-----+----------------+--------------+----------------+--------------------------------------------------
|  8 | Dedup          | 12           |                | outputVar: {                                    |
|    |                |              |                |   "colNames": [                                 |
|    |                |              |                |     "v"                                         |
|    |                |              |                |   ],                                            |
|    |                |              |                |   "type": "DATASET",                            |
|    |                |              |                |   "name": "__Dedup_8"                           |
|    |                |              |                | }                                               |
|    |                |              |                | inputVar: __Project_7                           |
-----+----------------+--------------+----------------+--------------------------------------------------
| 12 | Project        | 11           |                | outputVar: {                                    |
|    |                |              |                |   "colNames": [                                 |
|    |                |              |                |     "v"                                         |
|    |                |              |                |   ],                                            |
|    |                |              |                |   "type": "DATASET",                            |
|    |                |              |                |   "name": "__Project_7"                         |
|    |                |              |                | }                                               |
|    |                |              |                | inputVar: __Filter_11                           |
|    |                |              |                | columns: [                                      |
|    |                |              |                |   "$-.v AS v"                                   |
|    |                |              |                | ]                                               |
-----+----------------+--------------+----------------+--------------------------------------------------
| 11 | Filter         | 4            |                | outputVar: {                                    |
|    |                |              |                |   "colNames": [                                 |
|    |                |              |                |     "v",                                        |
|    |                |              |                |     "__VAR_1",                                  |
|    |                |              |                |     "__VAR_0"                                   |
|    |                |              |                |   ],                                            |
|    |                |              |                |   "type": "DATASET",                            |
|    |                |              |                |   "name": "__Filter_11"                         |
|    |                |              |                | }                                               |
|    |                |              |                | inputVar: __AppendVertices_4                    |
|    |                |              |                | condition: (properties($-.v).name CONTAINS "a") |
|    |                |              |                | isStable: false                                 |
-----+----------------+--------------+----------------+--------------------------------------------------
|  4 | AppendVertices | 3            |                | outputVar: {                                    |
|    |                |              |                |   "colNames": [                                 |
|    |                |              |                |     "v",                                        |
|    |                |              |                |     "__VAR_1",                                  |
|    |                |              |                |     "__VAR_0"                                   |
|    |                |              |                |   ],                                            |
|    |                |              |                |   "type": "DATASET",                            |
|    |                |              |                |   "name": "__AppendVertices_4"                  |
|    |                |              |                | }                                               |
|    |                |              |                | inputVar: __Traverse_3                          |
|    |                |              |                | space: 1                                        |
|    |                |              |                | dedup: true                                     |
|    |                |              |                | limit: -1                                       |
|    |                |              |                | filter:                                         |
|    |                |              |                | orderBy: []                                     |
|    |                |              |                | src: none_direct_dst($-.__VAR_1)                |
|    |                |              |                | props: [                                        |
|    |                |              |                |   {                                             |
|    |                |              |                |     "props": [                                  |
|    |                |              |                |       "name",                                   |
|    |                |              |                |       "age",                                    |
|    |                |              |                |       "_tag"                                    |
|    |                |              |                |     ],                                          |
|    |                |              |                |     "tagId": 2                                  |
|    |                |              |                |   },                                            |
|    |                |              |                |   {                                             |
|    |                |              |                |     "props": [                                  |
|    |                |              |                |       "name",                                   |
|    |                |              |                |       "_tag"                                    |
|    |                |              |                |     ],                                          |
|    |                |              |                |     "tagId": 3                                  |
|    |                |              |                |   }                                             |
|    |                |              |                | ]                                               |
|    |                |              |                | exprs:                                          |
|    |                |              |                | vertex_filter:                                  |
|    |                |              |                | if_track_previous_path: true                    |
-----+----------------+--------------+----------------+--------------------------------------------------
|  3 | Traverse       | 1            |                | outputVar: {                                    |
|    |                |              |                |   "colNames": [                                 |
|    |                |              |                |     "v",                                        |
|    |                |              |                |     "__VAR_1"                                   |
|    |                |              |                |   ],                                            |
|    |                |              |                |   "type": "DATASET",                            |
|    |                |              |                |   "name": "__Traverse_3"                        |
|    |                |              |                | }                                               |
|    |                |              |                | inputVar: __IndexScan_1                         |
|    |                |              |                | space: 1                                        |
|    |                |              |                | dedup: true                                     |
|    |                |              |                | limit: -1                                       |
|    |                |              |                | filter:                                         |
|    |                |              |                | orderBy: []                                     |
|    |                |              |                | src: $_vid                                      |
|    |                |              |                | edgeTypes: []                                   |
|    |                |              |                | edgeDirection: BOTH                             |
|    |                |              |                | vertexProps: [                                  |
|    |                |              |                |   {                                             |
|    |                |              |                |     "props": [                                  |
|    |                |              |                |       "name",                                   |
|    |                |              |                |       "age",                                    |
|    |                |              |                |       "_tag"                                    |
|    |                |              |                |     ],                                          |
|    |                |              |                |     "tagId": 2                                  |
|    |                |              |                |   },                                            |
|    |                |              |                |   {                                             |
|    |                |              |                |     "props": [                                  |
|    |                |              |                |       "name",                                   |
|    |                |              |                |       "_tag"                                    |
|    |                |              |                |     ],                                          |
|    |                |              |                |     "tagId": 3                                  |
|    |                |              |                |   }                                             |
|    |                |              |                | ]                                               |
|    |                |              |                | edgeProps: [                                    |
|    |                |              |                |   {                                             |
|    |                |              |                |     "props": [                                  |
|    |                |              |                |       "_dst",                                   |
|    |                |              |                |       "_rank",                                  |
|    |                |              |                |       "_type",                                  |
|    |                |              |                |       "_src"                                    |
|    |                |              |                |     ],                                          |
|    |                |              |                |     "type": "-5"                                |
|    |                |              |                |   },                                            |
|    |                |              |                |   {                                             |
|    |                |              |                |     "props": [                                  |
|    |                |              |                |       "_dst",                                   |
|    |                |              |                |       "_rank",                                  |
|    |                |              |                |       "_type",                                  |
|    |                |              |                |       "_src"                                    |
|    |                |              |                |     ],                                          |
|    |                |              |                |     "type": "5"                                 |
|    |                |              |                |   },                                            |
|    |                |              |                |   {                                             |
|    |                |              |                |     "props": [                                  |
|    |                |              |                |       "_dst",                                   |
|    |                |              |                |       "_rank",                                  |
|    |                |              |                |       "_type",                                  |
|    |                |              |                |       "_src"                                    |
|    |                |              |                |     ],                                          |
|    |                |              |                |     "type": "-4"                                |
|    |                |              |                |   },                                            |
|    |                |              |                |   {                                             |
|    |                |              |                |     "props": [                                  |
|    |                |              |                |       "_dst",                                   |
|    |                |              |                |       "_rank",                                  |
|    |                |              |                |       "_type",                                  |
|    |                |              |                |       "_src"                                    |
|    |                |              |                |     ],                                          |
|    |                |              |                |     "type": "4"                                 |
|    |                |              |                |   }                                             |
|    |                |              |                | ]                                               |
|    |                |              |                | statProps:                                      |
|    |                |              |                | exprs:                                          |
|    |                |              |                | random: false                                   |
|    |                |              |                | steps: 0..0                                     |
|    |                |              |                | vertex filter: player._tag IS NOT EMPTY         |
|    |                |              |                | edge filter:                                    |
|    |                |              |                | if_track_previous_path: false                   |
-----+----------------+--------------+----------------+--------------------------------------------------
|  1 | IndexScan      | 2            |                | outputVar: {                                    |
|    |                |              |                |   "colNames": [                                 |
|    |                |              |                |     "_vid"                                      |
|    |                |              |                |   ],                                            |
|    |                |              |                |   "type": "DATASET",                            |
|    |                |              |                |   "name": "__IndexScan_1"                       |
|    |                |              |                | }                                               |
|    |                |              |                | inputVar:                                       |
|    |                |              |                | space: 1                                        |
|    |                |              |                | dedup: false                                    |
|    |                |              |                | limit: 9223372036854775807                      |
|    |                |              |                | filter:                                         |
|    |                |              |                | orderBy: []                                     |
|    |                |              |                | schemaId: 2                                     |
|    |                |              |                | isEdge: false                                   |
|    |                |              |                | returnCols: [                                   |
|    |                |              |                |   "_vid"                                        |
|    |                |              |                | ]                                               |
|    |                |              |                | indexCtx: [                                     |
|    |                |              |                |   {                                             |
|    |                |              |                |     "columnHints": [],                          |
|    |                |              |                |     "filter": "",                               |
|    |                |              |                |     "index_id": 6                               |
|    |                |              |                |   }                                             |
|    |                |              |                | ]                                               |
-----+----------------+--------------+----------------+--------------------------------------------------
|  2 | Start          |              |                | outputVar: {                                    |
|    |                |              |                |   "colNames": [],                               |
|    |                |              |                |   "type": "DATASET",                            |
|    |                |              |                |   "name": "__Start_2"                           |
|    |                |              |                | }                                               |
-----+----------------+--------------+----------------+--------------------------------------------------
```

**Comment by Milittle** [comment]
> Interesting, so this pattern was to match vertices with/out any edges connected to them?

I think yes. and I will try my best to reproduce this problem again, but if you guys have any idea about source code. pls let me konw how to get the details about this. thx indeed.

**Comment by Shylock-Hg** [comment]
Hello, what's the version of nebula-graphd reporting the error?

**Comment by Milittle** [comment]
> Hello, what's the version of nebula-graphd reporting the error?

3.0.1, I think this problem cause by concurrently alter schema, which cause the meta schema data mess.

**Comment by Shylock-Hg** [comment]
> > Hello, what's the version of nebula-graphd reporting the error?
> 
> 3.0.1, I think this problem cause by concurrently alter schema, which cause the meta schema data mess.

But I don't see you mention concurrently alter schema in issue description, could you attach the whole operations?

**Comment by Sophie-Xie** [comment]
Closed it first, if you have some new info, you can open the issue again.
