### ISSUE TITLE
AuthFailedException: Insert userIpSessionCount to local cache failed

### ISSUE THREAD

**Issue by doublex** [vesoft-inc/nebula#4374]
After updating from `3.02` -> `3.1` 
We have a multi-threaded environment - I don't understand this error message:

````
Traceback (most recent call last):
File "/home/mastermind/harmony/nebulaapi.py", line 32, in execute
with connection.session_context(config.nebula['user'], config.nebula['pass']) as session:
File "/usr/local/lib/python3.9/contextlib.py", line 117, in __enter__
return next(self.gen)
File "/home/user/.local/lib/python3.9/site-packages/nebula3/gclient/net/ConnectionPool.py", line 130, in session_context
session = self.get_session(*args, **kwargs)
File "/home/user/.local/lib/python3.9/site-packages/nebula3/gclient/net/ConnectionPool.py", line 109, in get_session
auth_result = connection.authenticate(user_name, password)
File "/home/user/.local/lib/python3.9/site-packages/nebula3/gclient/net/Connection.py", line 112, in authenticate
raise AuthFailedException(resp.error_msg)
nebula3.Exception.AuthFailedException: b'Insert userIpSessionCount to local cache failed.'
````

**Comment by doublex** [comment]
I think this issue is gone in `nebula 3.2`

**Comment by doublex** [comment]
Happens also with `nebula 3.2`:

````
E20220722 19:11:24.176733 13831 GraphService.cpp:105] Create session for userName: nebulauser, ip: ::ffff:2.3.4 failed: Insert userIpSessionCount to local cache failed.
````

**Comment by wey-gu** [comment]
hi @doublex , I am suspecting that could this be an issue in the ipv6 env? could you help confirm you are on/configuring with ipv6 environment?

**Comment by wey-gu** [comment]
cc @Sophie-Xie

**Comment by doublex** [comment]
Would surprise me. The server network interface has an IPv6 configured.
But the python-client connects via an IPv4.

**Comment by Aiee** [comment]
This PR tests the compatibility of ipv6 https://github.com/vesoft-inc/nebula-python/pull/224
Feel free to reopen the issue if the problem remains.
