### ISSUE TITLE
 Possible deadlock in starting storaged

### ISSUE THREAD

**Issue by kikimo** [vesoft-inc/nebula#4473]
**Please check the FAQ documentation before raising an issue**

**Describe the bug (__required__)**

In a cluster with 4 storaged:

```txt
(root@nebula) [sf1000]> show hosts;
+-----------------+------+-----------+----------+--------------+----------------------+------------------------+---------+
| Host            | Port | HTTP port | Status   | Leader count | Leader distribution  | Partition distribution | Version |
+-----------------+------+-----------+----------+--------------+----------------------+------------------------+---------+
| "192.168.15.5"  | 9779 | 19669     | "ONLINE" | 0            | "No valid partition" | "sf1000:120"           | ""      |
| "192.168.15.6"  | 9779 | 19669     | "ONLINE" | 118          | "sf1000:118"         | "sf1000:120"           | ""      |
| "192.168.15.7"  | 9779 | 19669     | "ONLINE" | 2            | "sf1000:2"           | "sf1000:2"             | ""      |
| "192.168.15.11" | 9779 | 19669     | "ONLINE" | 0            | "No valid partition" | "sf1000:118"           | ""      |
+-----------------+------+-----------+----------+--------------+----------------------+------------------------+---------+
Got 4 rows (time spent 1641/16105 us)

Tue, 26 Jul 2022 16:25:58 CST
```

stop 192.168.15.11, delete its data dir, and start it again, execute `balance data removee  "192.168.15.11":9779 in nebula-console, we found that all the balance tasks failed:

```txt
| "18, 3:96"             | "192.168.15.11:9779->192.168.15.7:9779" | "FAILED"     | 2022-07-26T08:24:29.000000      | 2022-07-26T08:24:29.000000      | "SUCCEEDED" |
| "18, 3:97"             | "192.168.15.11:9779->192.168.15.7:9779" | "FAILED"     | 2022-07-26T08:24:29.000000      | 2022-07-26T08:24:29.000000      | "SUCCEEDED" |
| "18, 3:98"             | "192.168.15.11:9779->192.168.15.7:9779" | "FAILED"     | 2022-07-26T08:24:29.000000      | 2022-07-26T08:24:29.000000      | "SUCCEEDED" |
| "18, 3:99"             | "192.168.15.11:9779->192.168.15.7:9779" | "FAILED"     | 2022-07-26T08:24:29.000000      | 2022-07-26T08:24:29.000000      | "SUCCEEDED" |
| "18, 3:100"            | "192.168.15.11:9779->192.168.15.7:9779" | "FAILED"     | 2022-07-26T08:24:29.000000      | 2022-07-26T08:24:29.000000      | "SUCCEEDED" |
| "18, 3:101"            | "192.168.15.11:9779->192.168.15.7:9779" | "FAILED"     | 2022-07-26T08:24:29.000000      | 2022-07-26T08:24:29.000000      | "SUCCEEDED" |
| "18, 3:102"            | "192.168.15.11:9779->192.168.15.7:9779" | "FAILED"     | 2022-07-26T08:24:29.000000      | 2022-07-26T08:24:29.000000      | "SUCCEEDED" |
| "18, 3:103"            | "192.168.15.11:9779->192.168.15.7:9779" | "FAILED"     | 2022-07-26T08:24:29.000000      | 2022-07-26T08:24:29.000000      | "SUCCEEDED" |
| "18, 3:104"            | "192.168.15.11:9779->192.168.15.7:9779" | "FAILED"     | 2022-07-26T08:24:29.000000      | 2022-07-26T08:24:29.000000      | "SUCCEEDED" |
| "18, 3:105"            | "192.168.15.11:9779->192.168.15.7:9779" | "FAILED"     | 2022-07-26T08:24:29.000000      | 2022-07-26T08:24:29.000000      | "SUCCEEDED" |
| "18, 3:106"            | "192.168.15.11:9779->192.168.15.7:9779" | "FAILED"     | 2022-07-26T08:24:29.000000      | 2022-07-26T08:24:29.000000      | "SUCCEEDED" |
| "18, 3:107"            | "192.168.15.11:9779->192.168.15.7:9779" | "FAILED"     | 2022-07-26T08:24:29.000000      | 2022-07-26T08:24:29.000000      | "SUCCEEDED" |
| "18, 3:108"            | "192.168.15.11:9779->192.168.15.7:9779" | "FAILED"     | 2022-07-26T08:24:29.000000      | 2022-07-26T08:24:29.000000      | "SUCCEEDED" |
| "18, 3:109"            | "192.168.15.11:9779->192.168.15.7:9779" | "FAILED"     | 2022-07-26T08:24:29.000000      | 2022-07-26T08:24:29.000000      | "SUCCEEDED" |
| "18, 3:110"            | "192.168.15.11:9779->192.168.15.7:9779" | "FAILED"     | 2022-07-26T08:24:29.000000      | 2022-07-26T08:24:29.000000      | "SUCCEEDED" |
| "18, 3:111"            | "192.168.15.11:9779->192.168.15.7:9779" | "FAILED"     | 2022-07-26T08:24:29.000000      | 2022-07-26T08:24:29.000000      | "SUCCEEDED" |
| "18, 3:112"            | "192.168.15.11:9779->192.168.15.7:9779" | "FAILED"     | 2022-07-26T08:24:29.000000      | 2022-07-26T08:24:29.000000      | "SUCCEEDED" |
| "18, 3:113"            | "192.168.15.11:9779->192.168.15.7:9779" | "FAILED"     | 2022-07-26T08:24:29.000000      | 2022-07-26T08:24:29.000000      | "SUCCEEDED" |
| "18, 3:114"            | "192.168.15.11:9779->192.168.15.7:9779" | "FAILED"     | 2022-07-26T08:24:29.000000      | 2022-07-26T08:24:29.000000      | "SUCCEEDED" |
| "18, 3:115"            | "192.168.15.11:9779->192.168.15.7:9779" | "FAILED"     | 2022-07-26T08:24:29.000000      | 2022-07-26T08:24:29.000000      | "SUCCEEDED" |
| "18, 3:116"            | "192.168.15.11:9779->192.168.15.7:9779" | "FAILED"     | 2022-07-26T08:24:29.000000      | 2022-07-26T08:24:29.000000      | "SUCCEEDED" |
| "18, 3:117"            | "192.168.15.11:9779->192.168.15.7:9779" | "FAILED"     | 2022-07-26T08:24:29.000000      | 2022-07-26T08:24:29.000000      | "SUCCEEDED" |
| "18, 3:118"            | "192.168.15.11:9779->192.168.15.7:9779" | "FAILED"     | 2022-07-26T08:24:29.000000      | 2022-07-26T08:24:29.000000      | "SUCCEEDED" |
| "18, 3:119"            | "192.168.15.11:9779->192.168.15.7:9779" | "FAILED"     | 2022-07-26T08:24:29.000000      | 2022-07-26T08:24:29.000000      | "SUCCEEDED" |
| "18, 3:120"            | "192.168.15.11:9779->192.168.15.7:9779" | "FAILED"     | 2022-07-26T08:24:29.000000      | 2022-07-26T08:24:29.000000      | "SUCCEEDED" |
| "Total:118"            | "Succeeded:0"                           | "Failed:118" | "In Progress:0"                 | "Invalid:0"                     | ""          |
+------------------------+-----------------------------------------+--------------+---------------------------------+---------------------------------+-------------+
Got 120 rows (time spent 4885/132055 us)

Tue, 26 Jul 2022 16:52:19 CST

(root@nebula) [sf1000]>
```

next we found that 192.168.15.11 does not listening on its admin port 9887:

```txt
# netstat -natp | grep 9778
#
```

gdb attach to the storaged, we found that the storaged stuck at startup:

```txt
Thread 1 (Thread 0x7fe76bf352c0 (LWP 299809) "nebula-storaged"):
#0  0x00007fe76af07e29 in syscall () from /lib64/libc.so.6
#1  0x000000000258cd8e in folly::detail::futexWaitImpl(std::atomic<unsigned int> const*, unsigned int, std::chrono::time_point<std::chrono::_V2::system_clock, std::chrono::duration<long, std::ratio<1l, 1000000000l> > > const*, std::chrono::time_point<std::chrono::_V2::steady_clock, std::chrono::duration<long, std::ratio<1l, 1000000000l> > > const*, unsigned int) ()
#2  0x0000000001382cd9 in folly::detail::futexWaitUntil<std::atomic<unsigned int>, std::chrono::_V2::steady_clock, std::chrono::duration<long, std::ratio<1l, 1000000000l> > > (futex=futex@entry=0x7fffa79f46c8, expected=expected@entry=2, deadline=..., waitMask=waitMask@entry=4294967295) at /data/src/nebula-ent/build/third-party/install/include/folly/detail/Futex-inl.h:119
#3  0x00000000013dc454 in folly::detail::MemoryIdler::futexWaitUntil<std::atomic<unsigned int>, std::chrono::time_point<std::chrono::_V2::steady_clock, std::chrono::duration<long, std::ratio<1l, 1000000000l> > >, std::chrono::duration<long, std::ratio<1l, 1000000000l> > > (expected=2, waitMask=4294967295, stackToRetain=1024, timeoutVariationFrac=0.5, idleTimeout=..., deadline=..., fut=...) at /data/src/nebula-ent/build/third-party/install/include/folly/detail/MemoryIdler.h:164
#4  folly::Baton<true, std::atomic>::tryWaitSlow<std::chrono::_V2::steady_clock, std::chrono::duration<long, std::ratio<1l, 1000000000l> > > (this=this@entry=0x7fffa79f46c8, deadline=..., opt=...) at /data/src/nebula-ent/build/third-party/install/include/folly/synchronization/Baton.h:328
#5  0x0000000001f282f0 in folly::Baton<true, std::atomic>::wait (opt=..., this=0x7fffa79f46c8) at /data/src/nebula-ent/build/third-party/install/include/folly/synchronization/Baton.h:177
#6  nebula::kvstore::NebulaStore::loadPartFromDataPath (this=0x7fe76aa5a400) at /data/src/nebula-ent/src/kvstore/NebulaStore.cpp:268
#7  0x0000000001f288bd in nebula::kvstore::NebulaStore::init (this=this@entry=0x7fe76aa5a400) at /data/src/nebula-ent/src/kvstore/NebulaStore.cpp:109
#8  0x000000000137c8c5 in nebula::storage::StorageServer::getStoreInstance (this=0x7fe76aa2e540) at /data/src/nebula-ent/src/storage/StorageServer.cpp:83
#9  0x000000000137e2fa in nebula::storage::StorageServer::start (this=0x7fe76aa2e540) at /data/src/nebula-ent/src/storage/StorageServer.cpp:231
#10 0x000000000132bc41 in main (argc=<optimized out>, argv=<optimized out>) at /data/src/nebula-ent/src/daemons/StorageDaemon.cpp:176
Detaching from program: /usr/local/nebula-ent-hw/bin/nebula-storaged, process 299809
[Inferior 1 (process 299809) detached]

# strace -p 299809
strace: Process 299809 attached
futex(0x7fffa79f46c8, FUTEX_WAIT_BITSET_PRIVATE, 2, NULL, 0xffffffff^Cstrace: Process 299809 detached
 <detached ...>
[root@vesoft-192-168-15-7 gdb-11.1]#
```

the code that start listening at the admin port src/storage/StorageServer.cpp:275:

```cpp
    264   env_->verticesML_ = std::make_unique<VerticesMemLock>();
    265   env_->edgesML_ = std::make_unique<EdgesMemLock>();
    266   env_->adminStore_ = getAdminStoreInstance();
    267   env_->adminSeqId_ = getAdminStoreSeqId();
    268   taskMgr_ = AdminTaskManager::instance(env_.get());
    269   if (!taskMgr_->init()) {
    270     LOG(ERROR) << "Init task manager failed!";
    271     return false;
    272   }
    273
    274   storageServer_ = getStorageServer();
    275   adminServer_ = getAdminServer();
    276   internalStorageServer_ = getInternalServer();
    277   if (!storageServer_ || !adminServer_ || !internalStorageServer_) {
    278     return false;
    279   }
    280
    281   {
    282     std::lock_guard<std::mutex> lkStop(muStop_);
    283     if (serverStatus_ != STATUS_UNINITIALIZED) {
    284       // stop() called during start()
    285       return false;
    286     }
    287     serverStatus_ = STATUS_RUNNING;
    288   }
    289   return true;
    290 } 
```

but storaged stuck at src/nebula-ent/src/storage/StorageServer.cpp:231，which in turn stuck at src/nebula-ent/src/kvstore/NebulaStore.cpp:268:

```cpp
128 void NebulaStore::loadPartFromDataPath() {
 129   CHECK(!!options_.partMan_);
 130   LOG(INFO) << "Scan the local path, and init the spaces_";
 131   // avoid duplicate engine created
 132   std::unordered_set<std::pair<GraphSpaceID, PartitionID>> partSet;
 133   for (auto& path : options_.dataPaths_) {
 134     auto rootPath = folly::stringPrintf("%s/nebula", path.c_str());
 135     auto spaceDirs = fs::FileUtils::listAllDirsInDir(rootPath.c_str());
 136     for (auto& spaceDir : spaceDirs) {
 137       std::vector<GraphSpaceID> spaceIds;
 138       LOG(INFO) << "Scan data path \"" << rootPath << "/" << spaceDir << "\"";
 139       try {
 140         GraphSpaceID space;
 141         try {
 142           space = folly::to<GraphSpaceID>(spaceDir);
 143         } catch (const std::exception& ex) {
 144           LOG(ERROR) << folly::sformat("Data path {} invalid {}", spaceDir, ex.what());
 145           continue;
 146         }
 147
 148         if (space == 0) {
 149           // skip the system space, only handle data space here.
 150           continue;
 151         }
 152
 153         auto status = options_.partMan_->spaceExist(storeSvcAddr_, space);
 154         if (!status.ok()) {
 155           if (FLAGS_auto_remove_invalid_space) {
 156             auto spacePath = rootPath + "/" + std::to_string(space);
 157             LOG(INFO) << "Remove outdated space " << space << " in path " << spacePath;
 158             removeDir(spacePath);
 159           }
 160           continue;
 161         } else {
 162           spaceIds.emplace_back(space);
 163         }
 164
 165         // add PartInfo for each space
 166         {
 167           folly::RWSpinLock::WriteHolder wh(&lock_);
 168           LOG(INFO) << "Load space " << space << " from disk";
 169           this->spaces_.emplace(space, std::make_unique<SpacePartInfo>());
 170         }
 171
 172         for (const auto& spaceId : spaceIds) {
 173           // iterate space path to get all partitions
 174           auto spacePath = rootPath + "/" + std::to_string(spaceId);
 175           auto partDirs = fs::FileUtils::listAllDirsInDir(spacePath.c_str());
 176           std::vector<std::pair<PartitionID, std::string>> partsPath;
 177           for (const auto& partDir : partDirs) {
 178             try {
 179               auto partId = folly::to<PartitionID>(partDir);
 180               auto partPath = folly::stringPrintf("%s/%s", spacePath.c_str(), partDir.c_str());
 181               partsPath.emplace_back(partId, partPath);
 182             } catch (const std::exception& ex) {
 183               LOG(ERROR) << folly::sformat("Path {}/{} invalid {}", spacePath, partDir, ex.what()); 
  184               continue;
 185             }
 186           }
 187
 188           std::atomic<size_t> counter(partsPath.size());
 189           folly::Baton<true, std::atomic> baton;
 190           for (const auto& idPath : partsPath) {
 191             auto partId = idPath.first;
 192             auto partPath = idPath.second;
 193             // create kv engine
 194             KVEngine* enginePtr = nullptr;
 195             auto engine = newEngine(spaceId, partId, partPath, options_.walPath_);
 196             {
 197               folly::RWSpinLock::WriteHolder wh(&lock_);
 198               auto spaceIt = this->spaces_.find(spaceId);
 199               CHECK(spaceIt != this->spaces_.end());
 200               spaceIt->second->engines_.emplace(partId, std::move(engine));
 201               enginePtr = spaceIt->second->engines_[partId].get();
 202             }
 203
 204             auto peers = initRaftPeers(spaceId, partId, enginePtr);
 205             // if peers is empty, which means the part is invalid
 206             if (peers.size() == 0) {
 207               engine.reset();
 208               if (FLAGS_auto_remove_invalid_space) {
 209                 removeDir(partPath);
 210               }
 211               counter.fetch_sub(1);
 212               if (counter.load() == 0) {
 213                 baton.post();
 214               }
 215               continue;
 216             }
 217
 218             bgWorkers_->addTask(
 219                 [spaceId, partId, partPath, enginePtr, peers, &counter, &baton, this]() mutable {
 220                   bool isLearner = false;
 221                   std::vector<HostAddr> addrs;  // raft peers
 222                   for (auto& [addr, raftPeer] : peers.getPeers()) {
 223                     if (addr == raftAddr_) {  // self
 224                       if (raftPeer.status == Peer::Status::kLearner) {
 225                         isLearner = true;
 226                       }
 227                     } else {  // others
 228                       if (raftPeer.status == Peer::Status::kNormalPeer ||
 229                           raftPeer.status == Peer::Status::kPromotedPeer) {
 230                         addrs.emplace_back(addr);
 231                       }
 232                     }
 233                   }
 234                   auto part = newPart(spaceId, partId, partPath, enginePtr, isLearner, addrs);
 235                   LOG(INFO) << "Load part " << spaceId << ", " << partId << " from disk";
 236
 237                   // add learner peers
 238                   if (!isLearner) {
 239                     for (auto& [addr, raftPeer] : peers.getPeers()) { 
  240                       if (addr == raftAddr_) {
 241                         continue;
 242                       }
 243
 244                       if (raftPeer.status == Peer::Status::kLearner) {
 245                         part->addLearner(addr, true);
 246                       }
 247                     }
 248                   }
 249
 250                   // add part to space
 251                   {
 252                     folly::RWSpinLock::WriteHolder holder(&lock_);
 253                     auto spaceIter = spaces_.find(spaceId);
 254                     CHECK(spaceIter != spaces_.end());
 255                     // Check if part already exists.
 256                     // Prevent the same part from existing on different dataPaths.
 257                     auto ret = spaceIter->second->parts_.emplace(partId, part);
 258                     if (!ret.second) {
 259                       LOG(FATAL) << "Part already exists, partId " << partId;
 260                     }
 261                   }
 262                   counter.fetch_sub(1);
 263                   if (counter.load() == 0) {
 264                     baton.post();
 265                   }
 266                 });
 267           }
 268           baton.wait();
 269           LOG(INFO) << "Load space " << spaceId << " in path " << path << " complete";
 270         }
 271       } catch (std::exception& e) {
 272         LOG(FATAL) << "Invalid data directory \"" << spaceDir << "\"";
 273       }
 274     }
 275   }
 276 }
```

**Your Environments (__required__)**

* OS: `uname -a`
* Compiler: `g++ --version` or `clang++ --version`
* CPU: `lscpu`
* Commit id (e.g. `a3ffc7d8`)

**How To Reproduce(__required__)**

1. Step 1
2. Step 2
3. Step 3

**Expected behavior**

**Additional context**

**Comment by critical27** [comment]
I'll add no except in this lambda, hope we can find why deadlock
