### ISSUE TITLE
log into nebula without a password

### ISSUE THREAD

**Issue by foesa-yang** [vesoft-inc/nebula#4718]
**Please check the FAQ documentation before raising an issue**

**Describe the bug (__required__)**

How to log into nebula without a password？

**Your Environments (__required__)**

* OS: `uname -a`
* Compiler: `g++ --version` or `clang++ --version`
* CPU: `lscpu`
* Commit id (e.g. `a3ffc7d8`)

<img width="995" alt="image" src="https://user-images.githubusercontent.com/35463247/195322806-87f5775b-e0f4-4598-878b-32797d2c2741.png">

**How To Reproduce(__required__)**

1. First I created a user without password.
```
(root@nebula) [(none)]> create user foesa
Execution succeeded (time spent 4205/8811 us)

Wed, 12 Oct 2022 09:02:01 UTC
```

2. I tried to log in with `-p` and arbitrary password and without the configuration `-p`. Both ways can't log in to nebula.

```
[root@foesa foesa.yang]# ./nebula-console -addr 192.168.8.136 -port 9669 -u foesa -p nebula
2022/10/12 09:02:38 Fail to create a new session from connection pool, fail to authenticate, error: Invalid password
panic: Fail to create a new session from connection pool, fail to authenticate, error: Invalid password

goroutine 1 [running]:
log.Panicf(0x76c2b6, 0x35, 0xc00008de38, 0x1, 0x1)
	/opt/hostedtoolcache/go/1.16.4/x64/src/log/log.go:361 +0xc5
main.main()
	/home/runner/work/nebula-console/nebula-console/main.go:541 +0x9b9

[root@foesa foesa.yang]# ./nebula-console -addr 192.168.8.136 -port 9669 -u foesa
2022/10/12 09:02:41 Error: argument password is empty!
panic: Error: argument password is empty!

goroutine 1 [running]:
log.Panicf(0x76530d, 0x22, 0x0, 0x0, 0x0)
	/opt/hostedtoolcache/go/1.16.4/x64/src/log/log.go:361 +0xc5
main.validateFlags()
	/home/runner/work/nebula-console/nebula-console/main.go:473 +0x14f
main.main()
	/home/runner/work/nebula-console/nebula-console/main.go:503 +0x10b
```

3. And actually, I can use `show users` to see the user foesa.
```
(root@nebula) [(none)]> show users
+---------+--------------+
| Account | IP Whitelist |
+---------+--------------+
| "foesa" | ""           |
| "root"  | ""           |
+---------+--------------+
Got 2 rows (time spent 1104/2228 us)
```

**Expected behavior**

**Additional context**

**Comment by HarrisChu** [comment]
It should be a console issue, I can use blank password via nebula-go directly.
