### ISSUE TITLE
run concurrent test case, and then make graph core

### ISSUE THREAD

**Issue by HarrisChu** [vesoft-inc/nebula#4721]
debug the automatic doc test case, and when I run in 4 threads, it would make graph core.

version:
`2022.10.12-nightly`

```
#0  0x0000000001093204 in nebula::graph::ExpressionUtils::collectAll(nebula::Expression const*, std::unordered_set<nebula::Expression::Kind, std::hash<nebula::Expression::Kind>, std::equal_to<nebula::Expression::Kind>, std::allocator<nebula::Expression::Kind> > const&) ()
#1  0x000000000121c7ca in nebula::graph::MatchPlanner::connectMatchPlan(nebula::graph::SubPlan&, nebula::graph::MatchClauseContext*) ()
#2  0x000000000121d06e in nebula::graph::MatchPlanner::genQueryPartPlan(nebula::graph::QueryContext*, nebula::graph::SubPlan&, nebula::graph::QueryPart const&) ()
#3  0x000000000121d583 in nebula::graph::MatchPlanner::transform(nebula::graph::AstContext*) ()
#4  0x00000000012127b7 in nebula::graph::Planner::toPlan(nebula::graph::AstContext*) ()
#5  0x00000000011423de in nebula::graph::Validator::toPlan() ()
#6  0x00000000011432ee in nebula::graph::Validator::validate() ()
#7  0x000000000114f124 in nebula::graph::SequentialValidator::validateImpl() ()
#8  0x0000000001143282 in nebula::graph::Validator::validate() ()
#9  0x0000000001144b92 in nebula::graph::Validator::validate(nebula::Sentence*, nebula::graph::QueryContext*) ()
#10 0x00000000010ee1bd in nebula::graph::QueryInstance::validateAndOptimize() ()
#11 0x00000000010ee781 in nebula::graph::QueryInstance::execute() ()
#12 0x00000000010e93b5 in nebula::graph::QueryEngine::execute(std::unique_ptr<nebula::graph::RequestContext<nebula::ExecutionResponse>, std::default_delete<nebula::graph::RequestContext<nebula::ExecutionResponse> > >) ()
---Type <return> to continue, or q <return> to quit---
#13 0x00000000010b601b in nebula::graph::GraphService::future_executeWithParameter(long, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&, std::unordered_map<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >, nebula::Value, std::hash<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > >, std::equal_to<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > >, std::allocator<std::pair<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const, nebula::Value> > > const&)::{lambda(nebula::StatusOr<std::shared_ptr<nebula::graph::ClientSession> >)#1}::operator()(nebula::StatusOr<std::shared_ptr<nebula::graph::ClientSession> >) ()
#14 0x00000000010b6811 in _ZN5folly6detail8function14FunctionTraitsIFvRNS_7futures6detail8CoreBaseEONS_8Executor9KeepAliveIS7_EEPNS_17exception_wrapperEEE7callBigIZNS4_4CoreIN6nebula8StatusOrISt10shared_ptrINSH_5graph13ClientSessionEEEEE11setCallbackIZNS4_10FutureBaseISN_E18thenImplementationIZNOS_6FutureISN_E9thenValueIZNSK_12GraphService27future_executeWithParameterElRKNSt7__cxx1112basic_stringIcSt11char_traitsIcESaIcEEERKSt13unordered_mapIS12_NSH_5ValueESt4hashIS12_ESt8equal_toIS12_ESaISt4pairIS13_S16_EEEEUlSN_E_EENST_INS4_19valueCallableResultISN_T_E10value_typeEEEOS1J_EUlSA_ONS_3TryISN_EEE_NS4_25tryExecutorCallableResultISN_S1R_vEEEENSt9enable_ifIXntsrNT0_13ReturnsFutureE5valueENS1V_6ReturnEE4typeES1N_S1V_NS4_18InlineContinuationEEUlSA_S1Q_E_EEvS1N_OSJ_INS_14RequestContextEES20_EUlS6_SA_SC_E_EEvS6_SA_SC_RNS1_4DataE ()
#15 0x0000000002182dfc in ?? ()
#16 0x0000000001f388c7 in virtual thunk to apache::thrift::concurrency::FunctionRunner::run() ()
#17 0x000000000207a408 in apache::thrift::concurrency::ThreadManager::Impl::Worker::run() ()
#18 0x000000000207c50e in apache::thrift::concurrency::PthreadThread::threadMain(void*) ()
```

**Comment by HarrisChu** [comment]
refer https://github.com/vesoft-inc/nebula/pull/4670
