### ISSUE TITLE
Graphd crashed executing query

### ISSUE THREAD

**Issue by nebula-bots** [vesoft-inc/nebula#4777]
**Please check the FAQ documentation before raising an issue**

**Describe the bug (__required__)**

Graphd crashed executing the following query generated by fuzzer:

`optional match (v) Match(v)  where id(v) == "Tim Duncan" return *`

```txt
(root@nebula) [nba]> optional match (v) Match(v)  where id(v) == "Tim Duncan" return *
2022/10/24 18:04:43 Loop error, failed to reconnect, failed to verify client version: read tcp 172.27.0.3:52642->172.27.0.3:9669: read: connection reset by peer

Bye root!
Mon, 24 Oct 2022 18:04:43 CST

panic: Loop error, failed to reconnect, failed to verify client version: read tcp 172.27.0.3:52642->172.27.0.3:9669: read: connection reset by peer

goroutine 1 [running]:
log.Panicf(0x75bdcf, 0xe, 0xc000335e38, 0x1, 0x1)
        /opt/hostedtoolcache/go/1.16.4/x64/src/log/log.go:361 +0xc5
main.main()
        /home/runner/work/nebula-console/nebula-console/main.go:572 +0x5a8
root@graph1:~/nebula-chaos-cluster#
```

the crash stack:

```txt
[Thread debugging using libthread_db enabled]
Using host libthread_db library "/lib/x86_64-linux-gnu/libthread_db.so.1".
--Type <RET> for more, q to quit, c to continue without paging--
Core was generated by `/root/src/nebula-ent-fuzz/build/bin/nebula-graphd --flagfile /root/nebula-chaos'.
Program terminated with signal SIGSEGV, Segmentation fault.
#0  nebula::graph::PlanNode::outputVarPtr (this=0x0) at /data/src/nebula-ent-fuzz/src/graph/planner/plan/PlanNode.h:250
250         return outputVar_;
[Current thread is 1 (Thread 0x7f79ce1fd700 (LWP 152))]
(gdb) bt
#0  nebula::graph::PlanNode::outputVarPtr (this=0x0) at /data/src/nebula-ent-fuzz/src/graph/planner/plan/PlanNode.h:250
#1  nebula::graph::BinaryInputNode::BinaryInputNode (this=0x7f79cca340e0, qctx=<optimized out>, kind=<optimized out>, left=<optimized out>,
    right=<optimized out>) at /data/src/nebula-ent-fuzz/src/graph/planner/plan/PlanNode.cpp:454
#2  0x000000000141e4ae in nebula::graph::BiJoin::BiJoin (this=0x7f79cca340e0, qctx=0x354b0a0 <je_tcache_bin_info>,
    kind=nebula::graph::PlanNode::Kind::kShowZones, left=0x0, right=0x0, hashKeys=..., probeKeys=...)
    at /data/src/nebula-ent-fuzz/src/graph/planner/plan/Query.cpp:857
#3  0x00000000013da628 in nebula::graph::BiInnerJoin::BiInnerJoin (this=0x7f79cca340e0, qctx=0x354b0a0 <je_tcache_bin_info>, left=0xffffffffffff6770,
    right=0x7f7a048008c0, hashKeys=..., probeKeys=...) at /data/src/nebula-ent-fuzz/src/graph/planner/plan/Query.h:1742
#4  0x00000000013da4ad in nebula::ObjectPool::makeAndAdd<nebula::graph::BiInnerJoin, nebula::graph::QueryContext*&, nebula::graph::PlanNode*&, nebula::graph::PlanNode*&, std::vector<nebula::Expression*, std::allocator<nebula::Expression*> >, std::vector<nebula::Expression*, std::allocator<nebula::Expression*> > >
    (this=0x7f79cbc16040, args=..., args=..., args=..., args=..., args=...) at /data/src/nebula-ent-fuzz/src/common/base/ObjectPool.h:44
#5  0x000000000141ebb6 in nebula::graph::BiInnerJoin::make (qctx=0x7f79cca19460, left=0x0, right=0x0, hashKeys=..., probeKeys=...)
    at /data/src/nebula-ent-fuzz/src/graph/planner/plan/Query.h:1728
#6  nebula::graph::BiInnerJoin::clone (this=0x7f79cca331d0) at /data/src/nebula-ent-fuzz/src/graph/planner/plan/Query.cpp:889
#7  0x000000000139ec3f in nebula::opt::RemoveNoopProjectRule::transform (this=<optimized out>, octx=0x7f79cca0f1e0, matched=...)
    at /data/src/nebula-ent-fuzz/src/graph/optimizer/rule/RemoveNoopProjectRule.cpp:86
#8  0x0000000001399c09 in nebula::opt::OptGroup::explore (this=<optimized out>, rule=0x7f7a04608018)
    at /data/src/nebula-ent-fuzz/src/graph/optimizer/OptGroup.cpp:92
#9  0x000000000139a3ed in nebula::opt::OptGroup::exploreUntilMaxRound (this=0x7f79cca34c10, rule=0x7f7a04608018)
    at /data/src/nebula-ent-fuzz/src/graph/optimizer/OptGroup.cpp:134
#10 0x00000000013986a1 in nebula::opt::Optimizer::doExploration (this=0x7f79c66c8d40, octx=<optimized out>, rootGroup=0x7f79cca34c10)
    at /data/src/nebula-ent-fuzz/src/graph/optimizer/Optimizer.cpp:81
#11 0x0000000001398387 in nebula::opt::Optimizer::findBestPlan (this=0x7f79c66c8d40, qctx=0x7f79cca19460)
    at /data/src/nebula-ent-fuzz/src/graph/optimizer/Optimizer.cpp:43
#12 0x0000000001286935 in nebula::graph::QueryInstance::findBestPlan (this=0x7f79cbc08100)
    at /data/src/nebula-ent-fuzz/src/graph/service/QueryInstance.cpp:248
#13 0x000000000128581e in nebula::graph::QueryInstance::validateAndOptimize (this=0x7f79cbc08100)
    at /data/src/nebula-ent-fuzz/src/graph/service/QueryInstance.cpp:95
#14 0x0000000001284324 in nebula::graph::QueryInstance::execute (this=0x7f79cbc08100) at /data/src/nebula-ent-fuzz/src/graph/service/QueryInstance.cpp:41
#15 0x000000000128192b in nebula::graph::QueryEngine::execute (this=0x7f7a0470acc0, rctx=...)
    at /data/src/nebula-ent-fuzz/src/graph/service/QueryEngine.cpp:56
#16 0x0000000001255cca in nebula::graph::GraphService::future_executeWithParameter(long, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocat--Type <RET> for more, q to quit, c to continue without paging--
or<char> > const&, std::unordered_map<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >, nebula::Value, std::hash<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > >, std::equal_to<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > >, std::allocator<std::pair<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const, nebula::Value> > > const&)::$_1::operator()(nebula::StatusOr<std::shared_ptr<nebula::graph::ClientSession> >) (this=<optimized out>, ret=...)
    at /data/src/nebula-ent-fuzz/src/graph/service/GraphService.cpp:238
#17 folly::futures::detail::wrapInvoke<nebula::StatusOr<std::shared_ptr<nebula::graph::ClientSession> >, nebula::graph::GraphService::future_executeWithParameter(long, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&, std::unordered_map<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >, nebula::Value, std::hash<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > >, std::equal_to<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > >, std::allocator<std::pair<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const, nebula::Value> > > const&)::$_1>(folly::Try<nebula::StatusOr<std::shared_ptr<nebula::graph::ClientSession> > >&&, nebula::graph::GraphService::future_executeWithParameter(long, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&, std::unordered_map<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >, nebula::Value, std::hash<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > >, std::equal_to<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > >, std::allocator<std::pair<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const, nebula::Value> > > const&)::$_1&&)::{lambda()#1}::operator()() const (this=<optimized out>) at /data/src/nebula-ent-fuzz/build/third-party/install/include/folly/futures/Future-inl.h:98
#18 folly::futures::detail::InvokeResultWrapper<void>::wrapResult<folly::futures::detail::wrapInvoke<nebula::StatusOr<std::shared_ptr<nebula::graph::ClientSession> >, nebula::graph::GraphService::future_executeWithParameter(long, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&, std::unordered_map<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >, nebula::Value, std::hash<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > >, std::equal_to<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > >, std::allocator<std::pair<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const, nebula::Value> > > const&)::$_1>(folly::Try<nebula::StatusOr<std::shared_ptr<nebula::graph::ClientSession> > >&&, nebula::graph::GraphService::future_executeWithParameter(long, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&, std::unordered_map<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >, nebula::Value, std::hash<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > >, std::equal_to<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > >, std::allocator<std::pair<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const, nebula::Value> > > const&)::$_1&&)::{lambda()#1}>(folly::futures::detail::wrapInvoke<nebula::StatusOr<std::shared_ptr<nebula::graph::ClientSession> >, nebula::graph::GraphService::future_executeWithParameter(long, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&, std::unordered_map<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >, nebula::Value, std::hash<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > >, std::equal_to<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > >, std::allocator<std::pair<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const, nebula::Value> > > const&)::$_1>(folly::Try<nebula::StatusOr<std::shared_ptr<nebula::graph::ClientSession> > >&&, nebula::graph::GraphService::future_executeWithParameter(long, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&, std::unordered_map<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >, nebula::Value, std::hash<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > >, std::equal_to<std::__cxx11::basic_string<char, std::char_traits<char>, std::a--Type <RET> for more, q to quit, c to continue without paging--
llocator<char> > >, std::allocator<std::pair<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const, nebula::Value> > > const&)::$_1&&)::{lambda()#1}) (fn=...) at /data/src/nebula-ent-fuzz/build/third-party/install/include/folly/futures/Future-inl.h:90
#19 folly::futures::detail::wrapInvoke<nebula::StatusOr<std::shared_ptr<nebula::graph::ClientSession> >, nebula::graph::GraphService::future_executeWithParameter(long, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&, std::unordered_map<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >, nebula::Value, std::hash<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > >, std::equal_to<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > >, std::allocator<std::pair<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const, nebula::Value> > > const&)::$_1>(folly::Try<nebula::StatusOr<std::shared_ptr<nebula::graph::ClientSession> > >&&, nebula::graph::GraphService::future_executeWithParameter(long, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&, std::unordered_map<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >, nebula::Value, std::hash<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > >, std::equal_to<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > >, std::allocator<std::pair<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const, nebula::Value> > > const&)::$_1&&) (t=..., f=...)
    at /data/src/nebula-ent-fuzz/build/third-party/install/include/folly/futures/Future-inl.h:108
#20 folly::Future<nebula::StatusOr<std::shared_ptr<nebula::graph::ClientSession> > >::thenValue<nebula::graph::GraphService::future_executeWithParameter(long, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&, std::unordered_map<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >, nebula::Value, std::hash<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > >, std::equal_to<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > >, std::allocator<std::pair<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const, nebula::Value> > > const&)::$_1>(nebula::graph::GraphService::future_executeWithParameter(long, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&, std::unordered_map<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >, nebula::Value, std::hash<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > >, std::equal_to<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > >, std::allocator<std::pair<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const, nebula::Value> > > const&)::$_1&&) &&::{lambda(folly::Executor::KeepAlive<folly::Executor>&&, folly::Try<nebula::StatusOr<std::shared_ptr<nebula::graph::ClientSession> > >&&)#1}::operator()(folly::Executor::KeepAlive<folly::Executor>&&, folly::Try<nebula::StatusOr<std::shared_ptr<nebula::graph::ClientSession> > >&&) (this=<optimized out>, t=...) at /data/src/nebula-ent-fuzz/build/third-party/install/include/folly/futures/Future-inl.h:991
#21 folly::futures::detail::CoreCallbackState<folly::Unit, folly::Future<nebula::StatusOr<std::shared_ptr<nebula::graph::ClientSession> > >::thenValue<nebula::graph::GraphService::future_executeWithParameter(long, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&, std::unordered_map<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >, nebula::Value, std::hash<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > >, std::equal_to<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > >, std::allocator<std::pair<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const, nebula::Value> > > const&)::$_1>(nebula::graph::GraphService::future_executeWithParameter(long, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&, std::unordered_map<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >, nebula::Value, std::hash<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > >, std::equal_to<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > >, std::allocator<std::pair<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const, nebula::Value> > > const&)::$_1&&) &&::{lambda(folly::Executor::KeepAlive<folly::Executor>&&, folly::T--Type <RET> for more, q to quit, c to continue without paging--
ry<nebula::StatusOr<std::shared_ptr<nebula::graph::ClientSession> > >&&)#1}>::invoke<folly::Executor::KeepAlive<folly::Executor>, folly::Try<nebula::StatusOr<std::shared_ptr<nebula::graph::ClientSession> > > >(folly::Executor::KeepAlive<folly::Executor>&&, folly::Try<nebula::StatusOr<std::shared_ptr<nebula::graph::ClientSession> > >&&) (this=<optimized out>, args=..., args=...)
    at /data/src/nebula-ent-fuzz/build/third-party/install/include/folly/futures/Future-inl.h:144
#22 folly::futures::detail::detail_msvc_15_7_workaround::invoke<folly::futures::detail::tryExecutorCallableResult<nebula::StatusOr<std::shared_ptr<nebula::graph::ClientSession> >, folly::Future<nebula::StatusOr<std::shared_ptr<nebula::graph::ClientSession> > >::thenValue<nebula::graph::GraphService::future_executeWithParameter(long, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&, std::unordered_map<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >, nebula::Value, std::hash<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > >, std::equal_to<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > >, std::allocator<std::pair<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const, nebula::Value> > > const&)::$_1>(nebula::graph::GraphService::future_executeWithParameter(long, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&, std::unordered_map<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >, nebula::Value, std::hash<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > >, std::equal_to<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > >, std::allocator<std::pair<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const, nebula::Value> > > const&)::$_1&&) &&::{lambda(folly::Executor::KeepAlive<folly::Executor>&&, folly::Try<nebula::StatusOr<std::shared_ptr<nebula::graph::ClientSession> > >&&)#1}, void>, folly::futures::detail::CoreCallbackState<folly::Unit, {lambda(folly::Executor::KeepAlive<folly::Executor>&&, folly::Try<nebula::StatusOr<std::shared_ptr<nebula::graph::ClientSession> > >&&)#1}>, nebula::StatusOr<std::shared_ptr<nebula::graph::ClientSession> >, 0>(folly::futures::detail::tryExecutorCallableResult<nebula::StatusOr<std::shared_ptr<nebula::graph::ClientSession> >, folly::Future<nebula::StatusOr<std::shared_ptr<nebula::graph::ClientSession> > >::thenValue<nebula::graph::GraphService::future_executeWithParameter(long, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&, std::unordered_map<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >, nebula::Value, std::hash<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > >, std::equal_to<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > >, std::allocator<std::pair<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const, nebula::Value> > > const&)::$_1>(nebula::graph::GraphService::future_executeWithParameter(long, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&, std::unordered_map<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >, nebula::Value, std::hash<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > >, std::equal_to<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > >, std::allocator<std::pair<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const, nebula::Value> > > const&)::$_1&&) &&::{lambda(folly::Executor::KeepAlive<folly::Executor>&&, folly::Try<nebula::StatusOr<std::shared_ptr<nebula::graph::ClientSession> > >&&)#1}, void>, folly::futures::detail::CoreCallbackState<folly::Unit, {lambda(folly::Executor::KeepAlive<folly::Executor>&&, folly::Try<nebula::StatusOr<std::shared_ptr<nebula::graph::ClientSession> > >&&)#1}>&, folly::Executor::KeepAlive<folly::Executor>&&, folly::Try<nebula::StatusOr<std::shared_ptr<nebula::graph::ClientSession> > >&&) (
    state=..., ka=..., t=...) at /data/src/nebula-ent-fuzz/build/third-party/install/include/folly/futures/Future-inl.h:336
#23 folly::futures::detail::FutureBase<nebula::StatusOr<std::shared_ptr<nebula::graph::ClientSession> > >::thenImplementation<folly::Future<nebula::StatusOr<std::shared_ptr<nebula::graph::ClientSession> > >::thenValue<nebula::graph::GraphService::future_executeWithParameter(long, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&, std::unordered_map<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >, nebul--Type <RET> for more, q to quit, c to continue without paging--
a::Value, std::hash<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > >, std::equal_to<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > >, std::allocator<std::pair<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const, nebula::Value> > > const&)::$_1>(nebula::graph::GraphService::future_executeWithParameter(long, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&, std::unordered_map<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >, nebula::Value, std::hash<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > >, std::equal_to<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > >, std::allocator<std::pair<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const, nebula::Value> > > const&)::$_1&&) &&::{lambda(folly::Executor::KeepAlive<folly::Executor>&&, folly::Try<nebula::StatusOr<std::shared_ptr<nebula::graph::ClientSession> > >&&)#1}, folly::futures::detail::tryExecutorCallableResult<nebula::StatusOr<std::shared_ptr<nebula::graph::ClientSession> >, {lambda(folly::Executor::KeepAlive<folly::Executor>&&, folly::Try<nebula::StatusOr<std::shared_ptr<nebula::graph::ClientSession> > >&&)#1}, void> >(nebula::graph::GraphService::future_executeWithParameter(long, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&, std::unordered_map<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >, nebula::Value, std::hash<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > >, std::equal_to<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > >, std::allocator<std::pair<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const, nebula::Value> > > const&)::$_1&&, std::enable_if, folly::futures::detail::InlineContinuation)::{lambda(folly::Executor::KeepAlive<folly::Executor>&&, folly::Try<nebula::StatusOr<std::shared_ptr<nebula::graph::ClientSession> > >&&)#1}::operator()(folly::Executor::KeepAlive<folly::Executor>&&, folly::Try<nebula::StatusOr<std::shared_ptr<nebula::graph::ClientSession> > >&&)::{lambda()#1}::operator()() const (this=<optimized out>)
    at /data/src/nebula-ent-fuzz/build/third-party/install/include/folly/futures/Future-inl.h:383
#24 folly::makeTryWith<folly::futures::detail::FutureBase<nebula::StatusOr<std::shared_ptr<nebula::graph::ClientSession> > >::thenImplementation<folly::Future<nebula::StatusOr<std::shared_ptr<nebula::graph::ClientSession> > >::thenValue<nebula::graph::GraphService::future_executeWithParameter(long, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&, std::unordered_map<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >, nebula::Value, std::hash<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > >, std::equal_to<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > >, std::allocator<std::pair<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const, nebula::Value> > > const&)::$_1>(nebula::graph::GraphService::future_executeWithParameter(long, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&, std::unordered_map<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >, nebula::Value, std::hash<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > >, std::equal_to<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > >, std::allocator<std::pair<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const, nebula::Value> > > const&)::$_1&&) &&::{lambda(folly::Executor::KeepAlive<folly::Executor>&&, folly::Try<nebula::StatusOr<std::shared_ptr<nebula::graph::ClientSession> > >&&)#1}, folly::futures::detail::tryExecutorCallableResult<nebula::StatusOr<std::shared_ptr<nebula::graph::ClientSession> >, {lambda(folly::Executor::KeepAlive<folly::Executor>&&, folly::Try<nebula::StatusOr<std::shared_ptr<nebula::graph::ClientSession> > >&&)#1}, void> >(nebula::graph::GraphService::future_executeWithParameter(long, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&, std::unordered_map<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >, nebula::Value, std::hash<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > >, std::equal_to<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > >, std::allocator<std::pair<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const, nebula::Value> > > const&)::$_1&&, std::enable_if, folly::futures::detail::InlineContinuation)::{lambda(folly::--Type <RET> for more, q to quit, c to continue without paging--
Executor::KeepAlive<folly::Executor>&&, folly::Try<nebula::StatusOr<std::shared_ptr<nebula::graph::ClientSession> > >&&)#1}::operator()(folly::Executor::KeepAlive<folly::Executor>&&, folly::Try<nebula::StatusOr<std::shared_ptr<nebula::graph::ClientSession> > >&&)::{lambda()#1}> (f=...)
    at /data/src/nebula-ent-fuzz/build/third-party/install/include/folly/Try-inl.h:288
#25 folly::futures::detail::FutureBase<nebula::StatusOr<std::shared_ptr<nebula::graph::ClientSession> > >::thenImplementation<folly::Future<nebula::StatusOr<std::shared_ptr<nebula::graph::ClientSession> > >::thenValue<nebula::graph::GraphService::future_executeWithParameter(long, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&, std::unordered_map<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >, nebula::Value, std::hash<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > >, std::equal_to<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > >, std::allocator<std::pair<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const, nebula::Value> > > const&)::$_1>(nebula::graph::GraphService::future_executeWithParameter(long, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&, std::unordered_map<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >, nebula::Value, std::hash<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > >, std::equal_to<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > >, std::allocator<std::pair<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const, nebula::Value> > > const&)::$_1&&) &&::{lambda(folly::Executor::KeepAlive<folly::Executor>&&, folly::Try<nebula::StatusOr<std::shared_ptr<nebula::graph::ClientSession> > >&&)#1}, folly::futures::detail::tryExecutorCallableResult<nebula::StatusOr<std::shared_ptr<nebula::graph::ClientSession> >, {lambda(folly::Executor::KeepAlive<folly::Executor>&&, folly::Try<nebula::StatusOr<std::shared_ptr<nebula::graph::ClientSession> > >&&)#1}, void> >(nebula::graph::GraphService::future_executeWithParameter(long, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&, std::unordered_map<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >, nebula::Value, std::hash<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > >, std::equal_to<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > >, std::allocator<std::pair<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const, nebula::Value> > > const&)::$_1&&, std::enable_if, folly::futures::detail::InlineContinuation)::{lambda(folly::Executor::KeepAlive<folly::Executor>&&, folly::Try<nebula::StatusOr<std::shared_ptr<nebula::graph::ClientSession> > >&&)#1}::operator()(folly::Executor::KeepAlive<folly::Executor>&&, folly::Try<nebula::StatusOr<std::shared_ptr<nebula::graph::ClientSession> > >&&) (this=<optimized out>, ka=..., t=...)
    at /data/src/nebula-ent-fuzz/build/third-party/install/include/folly/futures/Future-inl.h:382
#26 _ZZN5folly7futures6detail4CoreIN6nebula8StatusOrISt10shared_ptrINS3_5graph13ClientSessionEEEEE11setCallbackIZNS1_10FutureBaseIS9_E18thenImplementationIZNOS_6FutureIS9_E9thenValueIZNS6_12GraphService27future_executeWithParameterElRKNSt7__cxx1112basic_stringIcSt11char_traitsIcESaIcEEERKSt13unordered_mapISO_NS3_5ValueESt4hashISO_ESt8equal_toISO_ESaISt4pairISP_SS_EEEE3$_1EENSF_INS1_19valueCallableResultIS9_T_E10value_typeEEEOS15_EUlONS_8Executor9KeepAliveIS1A_EEONS_3TryIS9_EEE_NS1_25tryExecutorCallableResultIS9_S1H_vEEEENSt9enable_ifIXntsrNT0_13ReturnsFutureE5valueENS1L_6ReturnEE4typeES19_S1L_NS1_18InlineContinuationEEUlS1D_S1G_E_EEvS19_OS5_INS_14RequestContextEES1P_ENUlRNS1_8CoreBaseES1D_PNS_17exception_wrapperEE_clES1V_S1D_S1X_ (this=0x7f79cbc5f000, coreBase=..., ka=...,
    ew=<optimized out>) at /data/src/nebula-ent-fuzz/build/third-party/install/include/folly/futures/detail/Core.h:637
#27 _ZN5folly6detail8function14FunctionTraitsIFvRNS_7futures6detail8CoreBaseEONS_8Executor9KeepAliveIS7_EEPNS_17exception_wrapperEEE7callBigIZNS4_4CoreIN6nebula8StatusOrISt10shared_ptrINSH_5graph13ClientSessionEEEEE11setCallbackIZNS4_10FutureBaseISN_E18thenImplementationIZNOS_6FutureISN_E9thenValueIZNSK_12GraphService27future_executeWithParameterElRKNSt7__cxx1112basic_stringIcSt11char_traitsIcESaIcEEERKSt13unordered_mapIS12_NSH_5ValueESt4hashIS12_ESt8equal_toIS12_ESaISt4pairIS13_S16_EEEE3$_1EENST_INS4_19valueCallableResultISN_T_E10value_typeEEEOS1J_EUlSA_ONS_3TryISN_EEE_NS4_25tryExecutorCallableResultISN_S1R_vEEEENSt9enable_--Type <RET> for more, q to quit, c to continue without paging--c
ifIXntsrNT0_13ReturnsFutureE5valueENS1V_6ReturnEE4typeES1N_S1V_NS4_18InlineContinuationEEUlSA_S1Q_E_EEvS1N_OSJ_INS_14RequestContextEES1Z_EUlS6_SA_SC_E_EEvS6_SA_SC_RNS1_4DataE (args=<optimized out>, args=<optimized out>, args=<optimized out>, p=...) at /data/src/nebula-ent-fuzz/build/third-party/install/include/folly/Function.h:385
#28 0x00000000025a3e5c in ?? ()
#29 0x0000000002324c07 in virtual thunk to apache::thrift::concurrency::FunctionRunner::run() ()
#30 0x000000000246cc38 in apache::thrift::concurrency::ThreadManager::Impl::Worker::run() ()
#31 0x000000000246ed3e in apache::thrift::concurrency::PthreadThread::threadMain(void*) ()
#32 0x00007f7a04c18609 in start_thread (arg=<optimized out>) at pthread_create.c:477
#33 0x00007f7a04b3f293 in clone () at ../sysdeps/unix/sysv/linux/x86_64/clone.S:95
```

**Your Environments (__required__)**

* OS: `uname -a`
* Compiler: `g++ --version` or `clang++ --version`
* CPU: `lscpu`
* Commit id (e.g. `a3ffc7d8`) 828922652

**How To Reproduce(__required__)**

1. Step 1
2. Step 2
3. Step 3

**Expected behavior**

**Additional context**

**Comment by Sophie-Xie** [comment]
#4780
