### ISSUE TITLE
graphd crash when executing `avg +1`

### ISSUE THREAD

**Issue by caton-hpg** [vesoft-inc/nebula#5111]
**Please check the FAQ documentation before raising an issue**

**Describe the bug (__required__)**

graphd crash when execute
```
(root@nebula) [nba]> $var=go from "Tim Duncan" over like yield like._dst as id, like.likeness as likeness;yield avg($var.likeness)+1
```

```
#0  __GI_raise (sig=sig@entry=6) at ../sysdeps/unix/sysv/linux/raise.c:50
#1  0x00007fe420da4859 in __GI_abort () at abort.c:79
#2  0x00000000053768aa in google::LogMessage::Fail() ()
#3  0x00000000053799a4 in google::LogMessage::SendToLog() ()
#4  0x0000000005376379 in google::LogMessage::Flush() ()
#5  0x000000000537a059 in google::LogMessageFatal::~LogMessageFatal() ()
#6  0x0000000003bb29f9 in nebula::graph::DefaultIter::getColumnIndex (this=0x7fe4044335d0) at /home/caton.hao/build_code/nebula/src/graph/context/Iterator.h:232
#7  0x0000000003b96fe4 in nebula::graph::QueryExpressionContext::getVarPropIndex (this=0x7fe4054f3bf0, var=..., prop=...) at /home/caton.hao/build_code/nebula/src/graph/context/QueryExpressionContext.cpp:47
#8  0x0000000004dc94a0 in nebula::VariablePropertyExpression::eval (this=0x7fe404442d30, ctx=...) at /home/caton.hao/build_code/nebula/src/common/expression/PropertyExpression.cpp:87
#9  0x0000000004dc8663 in nebula::AggregateExpression::eval (this=0x7fe404442dc0, ctx=...) at /home/caton.hao/build_code/nebula/src/common/expression/AggregateExpression.cpp:41
#10 0x00000000039ac22f in nebula::graph::AggregateExecutor::execute (this=0x7fe404443920) at /home/caton.hao/build_code/nebula/src/graph/executor/query/AggregateExecutor.cpp:80
#11 0x0000000003b806e5 in nebula::graph::AsyncMsgNotifyBasedScheduler::execute (this=0x7fe4044330c0, executor=0x7fe404443920) at /home/caton.hao/build_code/nebula/src/graph/scheduler/AsyncMsgNotifyBasedScheduler.cpp:221
```

**Your Environments (__required__)**

* OS: `uname -a` 
* Compiler: `g++ --version` or `clang++ --version`
* CPU: `lscpu`
* Commit id (e.g. `a3ffc7d8`)

**How To Reproduce(__required__)**

**Expected behavior**

**Additional context**

**Comment by xtcyclist** [comment]
Run into some unimplemented method.

**Comment by xtcyclist** [comment]
<img width="856" alt="image" src="https://user-images.githubusercontent.com/7731943/209533262-93956da4-9af8-420c-9668-b5c1774eb254.png">

The input var of the last aggregate has not been set correctly.
