### ISSUE TITLE
Graphd crash due to default iterator

### ISSUE THREAD

**Issue by czpmango** [vesoft-inc/nebula#5125]
**Your Environments (__required__)**
nebula v3.1

**How To Reproduce(__required__)**
```
$var=go from "Tim Duncan" over like yield like._dst as id, like.likeness as likeness;yield avg($var.likeness)+3 as v;
```
**Expected behavior**
Get the correct result.

**Comment by czpmango** [comment]
```
#0  __GI_raise (sig=sig@entry=6) at ../sysdeps/unix/sysv/linux/raise.c:50
#1  0x00007f30d0a4c859 in __GI_abort () at abort.c:79
#2  0x000000000564351a in google::LogMessage::Fail() ()
#3  0x0000000005646614 in google::LogMessage::SendToLog() ()
#4  0x0000000005642fe9 in google::LogMessage::Flush() ()
#5  0x00000000056431f5 in google::LogMessage::~LogMessage() ()
#6  0x0000000003c4065b in nebula::graph::DefaultIter::getColumnIndex (this=0x7f3098c2dde0) at /home/kyle.cao/workspace/fork/nebula/src/graph/context/Iterator.h:232
#7  0x0000000003c21151 in nebula::graph::QueryExpressionContext::getVarPropIndex (this=0x7f309a1f2de0, var=..., prop=...)
    at /home/kyle.cao/workspace/fork/nebula/src/graph/context/QueryExpressionContext.cpp:47
#8  0x000000000507a71d in nebula::VariablePropertyExpression::eval (this=0x7f3098c8ed30, ctx=...)
    at /home/kyle.cao/workspace/fork/nebula/src/common/expression/PropertyExpression.cpp:88
#9  0x00000000050795ef in nebula::AggregateExpression::eval (this=0x7f3098c8edc0, ctx=...) at /home/kyle.cao/workspace/fork/nebula/src/common/expression/AggregateExpression.cpp:41
#10 0x00000000039e59f9 in nebula::graph::AggregateExecutor::execute (this=0x7f3098c8f920) at /home/kyle.cao/workspace/fork/nebula/src/graph/executor/query/AggregateExecutor.cpp:80
#11 0x0000000003c06a00 in nebula::graph::AsyncMsgNotifyBasedScheduler::execute (this=0x7f3098c2d1b0, executor=0x7f3098c8f920)
    at /home/kyle.cao/workspace/fork/nebula/src/graph/scheduler/AsyncMsgNotifyBasedScheduler.cpp:221
#12 0x0000000003c0b59a in operator()<std::vector<nebula::Status> > (__closure=0x7f3098c16fd0, t=...)
    at /home/kyle.cao/workspace/fork/nebula/src/graph/scheduler/AsyncMsgNotifyBasedScheduler.cpp:158
#13 0x0000000003c07a62 in operator() (__closure=0x7f309a1f3080) at /home/kyle.cao/3rd/include/folly/futures/Future-inl.h:101
#14 0x0000000003c0b62e in folly::futures::detail::InvokeResultWrapperBase<folly::Future<nebula::Status> >::wrapResult<folly::futures::detail::wrapInvoke<std::vector<nebula::Status>, nebula::graph::AsyncMsgNotifyBasedScheduler::runExecutor(std::vector<folly::Future<nebula::Status> >&&, nebula::graph::Executor*, folly::Executor*) const::<lambda(auto:182&&)> >(folly::Try<std::vector<nebula::Status> >&&, nebula::graph::AsyncMsgNotifyBasedScheduler::runExecutor(std::vector<folly::Future<nebula::Status> >&&, nebula::graph::Executor*, folly::Executor*) const::<lambda(auto:182&&)>&&)::<lambda()> >(struct {...}) (fn=...) at /home/kyle.cao/3rd/include/folly/futures/Future-inl.h:73
#15 0x0000000003c07b12 in folly::futures::detail::wrapInvoke<std::vector<nebula::Status>, nebula::graph::AsyncMsgNotifyBasedScheduler::runExecutor(std::vector<folly::Future<nebula::Status> >&&, nebula::graph::Executor*, folly::Executor*) const::<lambda(auto:182&&)> >(folly::Try<std::vector<nebula::Status, std::allocator<nebula::Status> > > &&, struct {...} &&) (
    t=..., f=...) at /home/kyle.cao/3rd/include/folly/futures/Future-inl.h:108
```

**Comment by caton-hpg** [comment]
This bug has been fixed. #5111
