### ISSUE TITLE
Not able to connect to nebula graph , docker , from pyspark

### ISSUE THREAD

**Issue by DOT-py-sys** [vesoft-inc/nebula#5678]
I was trying to connect to nebula graph and perform read operation , but would not able to do it from pyspark . 
df2 = spark.read.format("com.vesoft.nebula.connector.NebulaDataSource")\
 .option("type", "vertex")\
 .option("spaceName","demo_basketballplayer")\
 .option("label","player")\
 .option("returnCols", "*")\
 .option("partitionNumber", 1)\
 .option("operateType", "read")\
 .option("metaAddress", "127.0.0.1:9669")\
 .option("user", "root")\
 .option("passwd", "nebula")\
 .load()

Error i am getting : 
raise Py4JJavaError(
py4j.protocol.Py4JJavaError: An error occurred while calling o43.load.
: com.facebook.thrift.TApplicationException: Method name getSpace not found
	at com.facebook.thrift.TApplicationException.read(TApplicationException.java:133)
	at com.vesoft.nebula.meta.MetaService$Client.recv_getSpace(MetaService.java:574)
	at com.vesoft.nebula.meta.MetaService$Client.getSpace(MetaService.java:549)
	at com.vesoft.nebula.client.meta.MetaClient.getSpace(MetaClient.java:240)
	at com.vesoft.nebula.client.meta.MetaClient.getTag(MetaClient.java:307)
	at com.vesoft.nebula.connector.nebula.MetaProvider.getTag(MetaProvider.scala:79)
	at com.vesoft.nebula.connector.NebulaUtils$.getSchema(NebulaUtils.scala:171)
	at com.vesoft.nebula.connector.NebulaDataSource.inferSchema(NebulaDataSource.scala:53)
	at org.apache.spark.sql.execution.datasources.v2.DataSourceV2Utils$.getTableFromProvider(DataSourceV2Utils.scala:90)
	at org.apache.spark.sql.execution.datasources.v2.DataSourceV2Utils$.loadV2Source(DataSourceV2Utils.scala:140)
	at org.apache.spark.sql.DataFrameReader.$anonfun$load$1(DataFrameReader.scala:209)
	at scala.Option.flatMap(Option.scala:271)

**Comment by wey-gu** [comment]
> Method name getSpace not found

```
.option("metaAddress", "127.0.0.1:9669")
```

Dear @DOT-py-sys 

The metad address expected a metad endpoint whereas the one filled here is a graphD address.

Another hint here is that Spark Connector reads data bypassing the graphd, it reads data from storaged to enable the highly performant graph analytical workload. But it brought us limitations on accessing storaged/metad from their address defined in configuration, where in docker they are the container name, thus to do so in docker env, we should run the spark/pyspark env in same docker network :-D

**Comment by DOT-py-sys** [comment]
Hi , 

This is the updated code . the metaddress and graphaddress is k8 cluster endpoints . Sorry i can't post the endpoints here . 

df.write.format("com.vesoft.nebula.connector.NebulaDataSource").mode(
                    "overwrite").option(
                    "srcPolicy", "").option(
                    "dstPolicy", "").option(
                    "type", "edge").option(
                    "randkField","").option(
                    "spaceName", "nebulapoc").option(
                    "label", "demo_poc").option(
                    "srcVertexField", "source_id").option(
                    "dstVertexField", "target_id").option(
                    "batch", 1).option(
                    "graphAddress", self.graph_svc).option(
                    "metaAddress", self.meta_svc).option(
                    "passwd", "nebula").option(
                    "user", self.username).option(
                    "operateType", "write").option(
                    "writeMode", "insert").save()

The df which i am trying to write to nebula has captured from neo4j . 
The graphD and metaD address is working because we are using this to write to Vertex . Using this same metad address ,

Please help .
